package rp3.marketforce.models;

import java.util.ArrayList;
import java.util.List;

import android.database.Cursor;

import rp3.data.entity.EntityBase;
import rp3.db.QueryDir;
import rp3.db.sqlite.DataBase;
import rp3.marketforce.db.Contract;
import rp3.util.CursorUtils;

public class Actividad extends EntityBase<Actividad>
{
	private long id;
	private String descripcion;
	private int idTarea;
	private int idTareaActividad;
	private int idTareaActividadPadre;
	private int IdTipoActividad;
	private int orden;
	private String tipo;
	private List<Actividad> actividades_hijas;

	@Override
	public long getID() {
		// TODO Auto-generated method stub
		return this.id;
	}

	@Override
	public void setID(long id) {
		this.id = id;
		
	}

	@Override
	public boolean isAutoGeneratedId() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public String getTableName() {
		// TODO Auto-generated method stub
		return Contract.Actividades.TABLE_NAME;
	}

	@Override
	public void setValues() {
		setValue(Contract.Actividades.COLUMN_DESCRIPCION, this.descripcion);
		setValue(Contract.Actividades.COLUMN_ORDEN, this.orden);
		setValue(Contract.Actividades.COLUMN_TAREA_ACTIVIDAD_ID, this.idTareaActividad);
		setValue(Contract.Actividades.COLUMN_TAREA_ACTIVIDAD_PADRE_ID, this.idTareaActividadPadre);
		setValue(Contract.Actividades.COLUMN_TAREA_ID, this.idTarea);
		setValue(Contract.Actividades.COLUMN_TIPO, this.tipo);
		setValue(Contract.Actividades.COLUMN_TIPO_ACTIVIDAD_ID, this.IdTipoActividad);
		
	}

	@Override
	public Object getValue(String key) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String getDescription() {
		// TODO Auto-generated method stub
		return null;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getIdTarea() {
		return idTarea;
	}

	public void setIdTarea(int idTarea) {
		this.idTarea = idTarea;
	}

	public int getIdTareaActividad() {
		return idTareaActividad;
	}

	public void setIdTareaActividad(int idTareaActividad) {
		this.idTareaActividad = idTareaActividad;
	}

	public int getIdTareaActividadPadre() {
		return idTareaActividadPadre;
	}

	public void setIdTareaActividadPadre(int idTareaActividadPadre) {
		this.idTareaActividadPadre = idTareaActividadPadre;
	}

	public int getIdTipoActividad() {
		return IdTipoActividad;
	}

	public void setIdTipoActividad(int idTipoActividad) {
		IdTipoActividad = idTipoActividad;
	}

	public int getOrden() {
		return orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public List<Actividad> getActividades_hijas() {
		return actividades_hijas;
	}

	public void setActividades_hijas(List<Actividad> actividades_hijas) {
		this.actividades_hijas = actividades_hijas;
	}
	
	public static List<Actividad> getActividadesGrupalesByTarea(DataBase db, long idTarea){
		
        String query = QueryDir.getQuery( Contract.Actividades.QUERY_ACTIVIDADES_GRUPALES );		
		Cursor c = db.rawQuery(query,""+idTarea);
		
		List<Actividad> actividades = new ArrayList<Actividad>();
		
		while(c.moveToNext())
		{
			Actividad act = new Actividad();
			act.setId(CursorUtils.getLong(c,Contract.Actividades._ID));
			act.setDescripcion(CursorUtils.getString(c,Contract.Actividades.COLUMN_DESCRIPCION));
			act.setOrden(CursorUtils.getInt(c,Contract.Actividades.COLUMN_ORDEN));
			act.setIdTareaActividad(CursorUtils.getInt(c,Contract.Actividades.COLUMN_TAREA_ACTIVIDAD_ID));
			act.setIdTareaActividadPadre(CursorUtils.getInt(c,Contract.Actividades.COLUMN_TAREA_ACTIVIDAD_PADRE_ID));
			act.setIdTarea(CursorUtils.getInt(c,Contract.Actividades.COLUMN_TAREA_ID));
			act.setTipo(CursorUtils.getString(c,Contract.Actividades.COLUMN_TIPO));
			act.setIdTipoActividad(CursorUtils.getInt(c,Contract.Actividades.COLUMN_TIPO_ACTIVIDAD_ID));
			act.setActividades_hijas(getActividadesHijas(db, idTarea, act.getIdTareaActividad()));
			
			actividades.add(act);
		}
		
		return actividades;
	}
	
	public static Actividad getActividadSimple(DataBase db, long idTarea, long idActividad){
		
        String query = QueryDir.getQuery( Contract.Actividades.QUERY_ACTIVIDAD_SIMPLE );		
		Cursor c = db.rawQuery(query,new String[] {""+idTarea, ""+idActividad});
		
		Actividad act = null;
		
		while(c.moveToNext())
		{
			act = new Actividad();
			act.setId(CursorUtils.getLong(c,Contract.Actividades._ID));
			act.setDescripcion(CursorUtils.getString(c,Contract.Actividades.COLUMN_DESCRIPCION));
			act.setOrden(CursorUtils.getInt(c,Contract.Actividades.COLUMN_ORDEN));
			act.setIdTareaActividad(CursorUtils.getInt(c,Contract.Actividades.COLUMN_TAREA_ACTIVIDAD_ID));
			act.setIdTareaActividadPadre(CursorUtils.getInt(c,Contract.Actividades.COLUMN_TAREA_ACTIVIDAD_PADRE_ID));
			act.setIdTarea(CursorUtils.getInt(c,Contract.Actividades.COLUMN_TAREA_ID));
			act.setTipo(CursorUtils.getString(c,Contract.Actividades.COLUMN_TIPO));
			act.setIdTipoActividad(CursorUtils.getInt(c,Contract.Actividades.COLUMN_TIPO_ACTIVIDAD_ID));
			act.setActividades_hijas(getActividadesHijas(db, idTarea, act.getIdTareaActividad()));
		}
		
		return act;
	}
	
	public static Actividad getActividadSimple(DataBase db, long idTarea){
		
        String query = QueryDir.getQuery( Contract.Actividades.QUERY_ACTIVIDAD_SIMPLE_NO_GRUPAL );		
		Cursor c = db.rawQuery(query,""+idTarea);
		
		Actividad act = null;
		
		while(c.moveToNext())
		{
			act = new Actividad();
			act.setId(CursorUtils.getLong(c,Contract.Actividades._ID));
			act.setDescripcion(CursorUtils.getString(c,Contract.Actividades.COLUMN_DESCRIPCION));
			act.setOrden(CursorUtils.getInt(c,Contract.Actividades.COLUMN_ORDEN));
			act.setIdTareaActividad(CursorUtils.getInt(c,Contract.Actividades.COLUMN_TAREA_ACTIVIDAD_ID));
			act.setIdTareaActividadPadre(CursorUtils.getInt(c,Contract.Actividades.COLUMN_TAREA_ACTIVIDAD_PADRE_ID));
			act.setIdTarea(CursorUtils.getInt(c,Contract.Actividades.COLUMN_TAREA_ID));
			act.setTipo(CursorUtils.getString(c,Contract.Actividades.COLUMN_TIPO));
			act.setIdTipoActividad(CursorUtils.getInt(c,Contract.Actividades.COLUMN_TIPO_ACTIVIDAD_ID));
			act.setActividades_hijas(getActividadesHijas(db, idTarea, act.getIdTareaActividad()));
		}
		
		return act;
	}
	
	public static List<Actividad> getActividadesHijas(DataBase db, long idTarea, long idPadre){
		
        String query = QueryDir.getQuery( Contract.Actividades.QUERY_ACTIVIDADES_HIJAS );		
		Cursor c = db.rawQuery(query, new String[] {""+idTarea, ""+idPadre});
		
		List<Actividad> actividades = new ArrayList<Actividad>();
		
		while(c.moveToNext())
		{
			Actividad act = new Actividad();
			act.setId(CursorUtils.getLong(c,Contract.Actividades._ID));
			act.setDescripcion(CursorUtils.getString(c,Contract.Actividades.COLUMN_DESCRIPCION));
			act.setOrden(CursorUtils.getInt(c,Contract.Actividades.COLUMN_ORDEN));
			act.setIdTareaActividad(CursorUtils.getInt(c,Contract.Actividades.COLUMN_TAREA_ACTIVIDAD_ID));
			act.setIdTareaActividadPadre(CursorUtils.getInt(c,Contract.Actividades.COLUMN_TAREA_ACTIVIDAD_PADRE_ID));
			act.setIdTarea(CursorUtils.getInt(c,Contract.Actividades.COLUMN_TAREA_ID));
			act.setTipo(CursorUtils.getString(c,Contract.Actividades.COLUMN_TIPO));
			act.setIdTipoActividad(CursorUtils.getInt(c,Contract.Actividades.COLUMN_TIPO_ACTIVIDAD_ID));
			
			actividades.add(act);
		}
		
		return actividades;
	}
	
}
