package rp3.marketforce.models;

import java.util.ArrayList;
import java.util.List;

import android.database.Cursor;

import rp3.db.sqlite.DataBase;
import rp3.marketforce.db.Contract;
import rp3.util.CursorUtils;

public class AgendaTareaOpciones extends rp3.data.entity.EntityBase<AgendaTareaOpciones>{

	private long id;
	private String descripcion;
	private int idAgenda;
	private int idRuta;
	private int idTarea;
	private int idTareaActividad;
	private int orden;
	
	@Override
	public long getID() {
		return id;
	}

	@Override
	public void setID(long id) {
		this.id = id;
	}

	@Override
	public boolean isAutoGeneratedId() {
		return true;
	}

	@Override
	public String getTableName() {
		return Contract.AgendaTareaOpciones.TABLE_NAME;
	}

	@Override
	public void setValues() {				
		setValue(Contract.AgendaTareaOpciones.COLUMN_DESCRIPCION, this.descripcion);						
		setValue(Contract.AgendaTareaOpciones.COLUMN_AGENDA_ID, this.idAgenda);
		setValue(Contract.AgendaTareaOpciones.COLUMN_RUTA_ID, this.idRuta);
		setValue(Contract.AgendaTareaOpciones.COLUMN_TAREA_ID, this.idTarea);
		setValue(Contract.AgendaTareaOpciones.COLUMN_TAREA_ACTIVIDAD_ID, this.idTareaActividad);
		setValue(Contract.AgendaTareaOpciones.COLUMN_ORDEN, this.orden);
	}

	@Override
	public Object getValue(String key) {
		return null;
	}

	@Override
	public String getDescription() {
		return null;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getIdAgenda() {
		return idAgenda;
	}

	public void setIdAgenda(int idAgenda) {
		this.idAgenda = idAgenda;
	}

	public int getIdRuta() {
		return idRuta;
	}

	public void setIdRuta(int idRuta) {
		this.idRuta = idRuta;
	}

	public int getIdTarea() {
		return idTarea;
	}

	public void setIdTarea(int idTarea) {
		this.idTarea = idTarea;
	}

	public int getIdTareaActividad() {
		return idTareaActividad;
	}

	public void setIdTareaActividad(int idTareaActividad) {
		this.idTareaActividad = idTareaActividad;
	}

	public int getOrden() {
		return orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}
	
	public static List<AgendaTareaOpciones> getOpciones(DataBase db, long id_tarea, long id_actividad)
	{
		List<AgendaTareaOpciones> list_opc = new ArrayList<AgendaTareaOpciones>();
		
		Cursor c = db.query(Contract.AgendaTareaOpciones.TABLE_NAME,
				new String[] {Contract.AgendaTareaOpciones._ID,Contract.AgendaTareaOpciones.COLUMN_AGENDA_ID, Contract.AgendaTareaOpciones.COLUMN_DESCRIPCION,
				Contract.AgendaTareaOpciones.COLUMN_ORDEN,Contract.AgendaTareaOpciones.COLUMN_RUTA_ID, 
				Contract.AgendaTareaOpciones.COLUMN_TAREA_ACTIVIDAD_ID, Contract.AgendaTareaActividades.COLUMN_TAREA_ID},
				Contract.AgendaTareaOpciones.COLUMN_TAREA_ID + " = ? AND " +
				Contract.AgendaTareaOpciones.COLUMN_TAREA_ACTIVIDAD_ID + " = ?", new String[] {id_tarea + "", id_actividad + ""},
				null, null, Contract.AgendaTareaOpciones.COLUMN_ORDEN);
		
		if(c.moveToFirst())
		{
			do
			{
				AgendaTareaOpciones opcion = new AgendaTareaOpciones();
				opcion.setID(CursorUtils.getLong(c, Contract.AgendaTareaOpciones._ID));
				opcion.setIdAgenda(CursorUtils.getInt(c, Contract.AgendaTareaOpciones.COLUMN_AGENDA_ID));
				opcion.setDescripcion(CursorUtils.getString(c, Contract.AgendaTareaOpciones.COLUMN_DESCRIPCION));
				opcion.setOrden(CursorUtils.getInt(c, Contract.AgendaTareaOpciones.COLUMN_ORDEN));
				opcion.setIdRuta(CursorUtils.getInt(c, Contract.AgendaTareaOpciones.COLUMN_RUTA_ID));
				opcion.setIdTareaActividad(CursorUtils.getInt(c, Contract.AgendaTareaOpciones.COLUMN_TAREA_ACTIVIDAD_ID));
				opcion.setIdTarea(CursorUtils.getInt(c, Contract.AgendaTareaOpciones.COLUMN_TAREA_ID));
				list_opc.add(opcion);
			}while(c.moveToNext());
		}
		
		return list_opc;
	}
	
	public static void deleteOpciones(DataBase db, long idRuta, long idAgenda, long idTarea, long idAct)
	{
		db.delete(Contract.AgendaTareaOpciones.TABLE_NAME, Contract.AgendaTareaOpciones.COLUMN_TAREA_ID + " = ? AND " +
				Contract.AgendaTareaOpciones.COLUMN_AGENDA_ID + " = ? AND " +
				Contract.AgendaTareaOpciones.COLUMN_TAREA_ACTIVIDAD_ID + " = ? AND " +
				Contract.AgendaTareaOpciones.COLUMN_RUTA_ID + " = ?", new String[] {idTarea + "", idAgenda + "", idAct + "", idRuta + ""});
	}
}
