package rp3.marketforce.models;

import rp3.marketforce.db.Contract;

public class AgendaTareaOpciones extends rp3.data.entity.EntityBase<AgendaTareaOpciones>{

	private long id;
	private String descripcion;
	private int idAgenda;
	private int idRuta;
	private int idTarea;
	private int idTareaActividad;
	private int orden;
	
	@Override
	public long getID() {
		return id;
	}

	@Override
	public void setID(long id) {
		this.id = id;
	}

	@Override
	public boolean isAutoGeneratedId() {
		return false;
	}

	@Override
	public String getTableName() {
		return Contract.AgendaTareaOpciones.TABLE_NAME;
	}

	@Override
	public void setValues() {
		setValue(Contract.AgendaTareaOpciones._ID, this.id);				
		setValue(Contract.AgendaTareaOpciones.COLUMN_DESCRIPCION, this.descripcion);						
		setValue(Contract.AgendaTareaOpciones.COLUMN_AGENDA_ID, this.idAgenda);
		setValue(Contract.AgendaTareaOpciones.COLUMN_RUTA_ID, this.idRuta);
		setValue(Contract.AgendaTareaOpciones.COLUMN_TAREA_ID, this.idTarea);
		setValue(Contract.AgendaTareaOpciones.COLUMN_TAREA_ACTIVIDAD_ID, this.idTareaActividad);
		setValue(Contract.AgendaTareaOpciones.COLUMN_ORDEN, this.orden);
	}

	@Override
	public Object getValue(String key) {
		return null;
	}

	@Override
	public String getDescription() {
		return null;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getIdAgenda() {
		return idAgenda;
	}

	public void setIdAgenda(int idAgenda) {
		this.idAgenda = idAgenda;
	}

	public int getIdRuta() {
		return idRuta;
	}

	public void setIdRuta(int idRuta) {
		this.idRuta = idRuta;
	}

	public int getIdTarea() {
		return idTarea;
	}

	public void setIdTarea(int idTarea) {
		this.idTarea = idTarea;
	}

	public int getIdTareaActividad() {
		return idTareaActividad;
	}

	public void setIdTareaActividad(int idTareaActividad) {
		this.idTareaActividad = idTareaActividad;
	}

	public int getOrden() {
		return orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}
}
