package rp3.marketforce.models;

import java.util.ArrayList;
import java.util.List;

import android.database.Cursor;
import rp3.db.sqlite.DataBase;
import rp3.marketforce.db.Contract;
import rp3.util.CursorUtils;


public class Canal extends rp3.data.entity.EntityBase<Canal>{

	private long id;
	private String descripcion;
	
	@Override
	public long getID() {
		return id;
	}

	@Override
	public void setID(long id) {
		this.id = id;
	}

	@Override
	public boolean isAutoGeneratedId() {
		return false;
	}

	@Override
	public String getTableName() {
		return Contract.Canal.TABLE_NAME;
	}

	@Override
	public void setValues() {
		
		setValue(Contract.Canal._ID, this.id);
		setValue(Contract.Canal.COLUMN_DESCRIPCION, this.descripcion);
		
	}

	@Override
	public Object getValue(String key) {
		return null;
	}

	@Override
	public String getDescription() {
		return this.descripcion;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public static List<Canal> getCanal(DataBase db, String code){
		Cursor c = db.query(Contract.Canal.TABLE_NAME, new String[]{
			Contract.Canal._ID,
			Contract.Canal.COLUMN_DESCRIPCION
		});
		
		List<Canal> list = new ArrayList<Canal>();
		while(c.moveToNext()){
			 Canal tpcl = new Canal();
			tpcl.setID(CursorUtils.getLong(c, Contract.Canal._ID));
			tpcl.setDescripcion(CursorUtils.getString(c, Contract.Canal.FIELD_DESCRIPCION));
		
			list.add(tpcl);
		}
        c.close();
		return list;
	}

	
}
