package rp3.marketforce.models;

import java.util.ArrayList;
import java.util.List;

import android.database.Cursor;

import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;
import rp3.marketforce.db.Contract;
import rp3.util.CursorUtils;

public class Tarea extends EntityBase<Tarea>
{
	private long id;
	private int idTarea;
	private String nombreTarea;
	private String tipoTarea;
	private String estadoTarea;
	private String estadoTareaDescripcion;
	private List<Actividad> actividades;

	@Override
	public long getID() {
		// TODO Auto-generated method stub
		return id;
	}

	@Override
	public void setID(long id) {
		this.id = id;
		
	}

	@Override
	public boolean isAutoGeneratedId() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public String getTableName() {
		// TODO Auto-generated method stub
		return Contract.Tareas.TABLE_NAME;
	}

	@Override
	public void setValues() {
		setValue(Contract.Tareas.COLUMN_TAREA_ID, this.idTarea);
		setValue(Contract.Tareas.COLUMN_NOMBRE_TAREA, this.nombreTarea);
		setValue(Contract.Tareas.COLUMN_ESTADO_TAREA, this.estadoTarea);
		setValue(Contract.Tareas.COLUMN_TIPO_TAREA, this.tipoTarea);
		
	}

	@Override
	public Object getValue(String key) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String getDescription() {
		// TODO Auto-generated method stub
		return null;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public int getIdTarea() {
		return idTarea;
	}

	public void setIdTarea(int idTarea) {
		this.idTarea = idTarea;
	}

	public String getNombreTarea() {
		return nombreTarea;
	}

	public void setNombreTarea(String nombreTarea) {
		this.nombreTarea = nombreTarea;
	}

	public String getTipoTarea() {
		return tipoTarea;
	}

	public void setTipoTarea(String tipoTarea) {
		this.tipoTarea = tipoTarea;
	}

	public String getEstadoTarea() {
		return estadoTarea;
	}

	public void setEstadoTarea(String estadoTarea) {
		this.estadoTarea = estadoTarea;
	}

	public String getEstadoTareaDescripcion() {
		return estadoTareaDescripcion;
	}

	public void setEstadoTareaDescripcion(String estadoTareaDescripcion) {
		this.estadoTareaDescripcion = estadoTareaDescripcion;
	}

	public List<Actividad> getActividades() {
		return actividades;
	}

	public void setActividades(List<Actividad> actividades) {
		this.actividades = actividades;
	}
	
	public static List<Tarea> getTareas(DataBase db)
{
    Cursor c = db.query(Contract.Tareas.TABLE_NAME, new String[]{ Contract.Tareas.COLUMN_TAREA_ID, Contract.Tareas.COLUMN_NOMBRE_TAREA,
            Contract.Tareas.COLUMN_ESTADO_TAREA, Contract.Tareas.COLUMN_TIPO_TAREA});
    List<Tarea> tareas = new ArrayList<Tarea>();

    if(c.moveToFirst())
    {
        do
        {
            Tarea tarea = new Tarea();
            tarea.setIdTarea(CursorUtils.getInt(c, Contract.Tareas.COLUMN_TAREA_ID));
            tarea.setNombreTarea(CursorUtils.getString(c, Contract.Tareas.COLUMN_NOMBRE_TAREA));
            tarea.setTipoTarea(CursorUtils.getString(c, Contract.Tareas.COLUMN_TIPO_TAREA));
            tarea.setEstadoTarea(CursorUtils.getString(c, Contract.Tareas.COLUMN_ESTADO_TAREA));
            tareas.add(tarea);
        }while(c.moveToNext());
    }

    return tareas;

}

    public static Tarea getTareaId(DataBase db, int id)
    {
        Cursor c = db.query(Contract.Tareas.TABLE_NAME, new String[]{ Contract.Tareas.COLUMN_TAREA_ID, Contract.Tareas.COLUMN_NOMBRE_TAREA,
                Contract.Tareas.COLUMN_ESTADO_TAREA, Contract.Tareas.COLUMN_TIPO_TAREA}, Contract.Tareas.COLUMN_TAREA_ID + " = ?", id+"");
        Tarea tarea = null;
        if(c.moveToFirst())
        {
            do
            {
                tarea = new Tarea();
                tarea.setIdTarea(CursorUtils.getInt(c, Contract.Tareas.COLUMN_TAREA_ID));
                tarea.setNombreTarea(CursorUtils.getString(c, Contract.Tareas.COLUMN_NOMBRE_TAREA));
                tarea.setTipoTarea(CursorUtils.getString(c, Contract.Tareas.COLUMN_TIPO_TAREA));
                tarea.setEstadoTarea(CursorUtils.getString(c, Contract.Tareas.COLUMN_ESTADO_TAREA));
            }while(c.moveToNext());
        }

        return tarea;

    }
	
}
