package rp3.marketforce.models;

import java.util.ArrayList;
import java.util.List;

import android.database.Cursor;
import rp3.db.sqlite.DataBase;
import rp3.marketforce.db.Contract;
import rp3.util.CursorUtils;


public class TipoCliente extends rp3.data.entity.EntityBase<TipoCliente>{

	private long id;
	private String descripcion;
	
	@Override
	public long getID() {
		return id;
	}

	@Override
	public void setID(long id) {
		this.id = id;
	}

	@Override
	public boolean isAutoGeneratedId() {
		return false;
	}

	@Override
	public String getTableName() {
		return Contract.TipoCliente.TABLE_NAME;
	}

	@Override
	public void setValues() {
		
		setValue(Contract.TipoCliente._ID, this.id);
		setValue(Contract.TipoCliente.COLUMN_DESCRIPCION, this.descripcion);
		
	}

	@Override
	public Object getValue(String key) {
		return null;
	}

	@Override
	public String getDescription() {
		return this.descripcion;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public static List<TipoCliente> getTipoCliente(DataBase db, String code){
		Cursor c = db.query(Contract.TipoCliente.TABLE_NAME, new String[]{
			Contract.TipoCliente._ID,
			Contract.TipoCliente.COLUMN_DESCRIPCION
		});
		
		List<TipoCliente> list = new ArrayList<TipoCliente>();
		while(c.moveToNext()){
			 TipoCliente tpcl = new TipoCliente();
			tpcl.setID(CursorUtils.getInt(c, Contract.TipoCliente._ID));
			tpcl.setDescripcion(CursorUtils.getString(c, Contract.TipoCliente.FIELD_DESCRIPCION));
		
			list.add(tpcl);
		}
		return list;
	}
	
}
