package rp3.marketforce.models.oportunidad;

import android.database.Cursor;

import java.util.ArrayList;
import java.util.List;

import rp3.data.entity.EntityBase;
import rp3.db.QueryDir;
import rp3.db.sqlite.DataBase;
import rp3.marketforce.db.Contract;
import rp3.util.CursorUtils;

/**
 * Created by magno_000 on 15/05/2015.
 */
public class EtapaTarea extends EntityBase<EtapaTarea> {

    private long id;
    private int idEtapa;
    private int idTarea;
    private int orden;

    @Override
    public long getID() {
        return id;
    }

    @Override
    public void setID(long id) {
        this.id = id;
    }

    public int getIdEtapa() {
        return idEtapa;
    }

    public void setIdEtapa(int idEtapa) {
        this.idEtapa = idEtapa;
    }

    public int getIdTarea() {
        return idTarea;
    }

    public void setIdTarea(int idTarea) {
        this.idTarea = idTarea;
    }

    public int getOrden() {
        return orden;
    }

    public void setOrden(int orden) {
        this.orden = orden;
    }

    @Override
    public boolean isAutoGeneratedId() {
        return true;
    }

    @Override
    public String getTableName() {
        return Contract.EtapaTarea.TABLE_NAME;
    }

    @Override
    public void setValues() {
        setValue(Contract.EtapaTarea.COLUMN_ID_ETAPA, this.idEtapa);
        setValue(Contract.EtapaTarea.COLUMN_ID_TAREA, this.idTarea);
        setValue(Contract.EtapaTarea.COLUMN_ORDEN, this.orden);
    }

    @Override
    public Object getValue(String key) {
        return null;
    }

    @Override
    public String getDescription() {
        return null;
    }

    public static List<EtapaTarea> getEtapaTareas(DataBase dataBase) {
        String query = QueryDir.getQuery(Contract.EtapaTarea.QUERY_ETAPAS);

        Cursor c = dataBase.rawQuery(query);

        List<EtapaTarea> list = new ArrayList<EtapaTarea>();
        while(c.moveToNext()){
            EtapaTarea etp = new EtapaTarea();
            etp.setID(CursorUtils.getInt(c, Contract.EtapaTarea._ID));
            etp.setIdEtapa(CursorUtils.getInt(c, Contract.EtapaTarea.COLUMN_ID_ETAPA));
            etp.setIdTarea(CursorUtils.getInt(c, Contract.EtapaTarea.COLUMN_ID_TAREA));
            etp.setOrden(CursorUtils.getInt(c, Contract.EtapaTarea.COLUMN_ORDEN));
            list.add(etp);
        }
        return list;
    }
}
