package rp3.marketforce.models.oportunidad;

import android.database.Cursor;

import java.util.ArrayList;
import java.util.List;

import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;
import rp3.marketforce.db.Contract;
import rp3.util.CursorUtils;

/**
 * Created by magno_000 on 14/05/2015.
 */
public class Etapa extends EntityBase<Etapa> {

    private long id;
    private int idEtapa;
    private String descripcion;

    @Override
    public long getID() {
        return id;
    }

    @Override
    public void setID(long id) {
        this.id = id;
    }

    public int getIdEtapa() {
        return idEtapa;
    }

    public void setIdEtapa(int idEtapa) {
        this.idEtapa = idEtapa;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Override
    public boolean isAutoGeneratedId() {
        return true;
    }

    @Override
    public String getTableName() {
        return Contract.Etapa.TABLE_NAME;
    }

    @Override
    public void setValues() {
        setValue(Contract.Etapa.COLUMN_ID_ETAPA, this.idEtapa);
        setValue(Contract.Etapa.COLUMN_DESCRIPCION, this.descripcion);
    }

    @Override
    public Object getValue(String key) {
        return null;
    }

    @Override
    public String getDescription() {
        return null;
    }

    public static List<Etapa> getEtapas(DataBase db){

        Cursor c = db.query(Contract.Etapa.TABLE_NAME, new String[] {Contract.Etapa._ID, Contract.Etapa.COLUMN_ID_ETAPA,
                        Contract.Etapa.COLUMN_DESCRIPCION});

        List<Etapa> list = new ArrayList<Etapa>();
        while(c.moveToNext()){
            Etapa etp = new Etapa();
            etp.setID(CursorUtils.getInt(c, Contract.Etapa._ID));
            etp.setIdEtapa(CursorUtils.getInt(c, Contract.Etapa.COLUMN_ID_ETAPA));
            etp.setDescripcion(CursorUtils.getString(c, Contract.Etapa.COLUMN_DESCRIPCION));
            list.add(etp);
        }
        return list;
    }

    public static Etapa getEtapaById(DataBase db, int idEtapa) {
        Cursor c = db.query(Contract.Etapa.TABLE_NAME, new String[] {Contract.Etapa._ID, Contract.Etapa.COLUMN_ID_ETAPA,
                Contract.Etapa.COLUMN_DESCRIPCION}, Contract.Etapa.COLUMN_ID_ETAPA + " = ? ", new String[] {idEtapa + ""} );

        Etapa etp = new Etapa();
        while(c.moveToNext()){
            etp.setID(CursorUtils.getInt(c, Contract.Etapa._ID));
            etp.setIdEtapa(CursorUtils.getInt(c, Contract.Etapa.COLUMN_ID_ETAPA));
            etp.setDescripcion(CursorUtils.getString(c, Contract.Etapa.COLUMN_DESCRIPCION));
        }
        return etp;
    }
}
