package rp3.marketforce.models.oportunidad;

import android.database.Cursor;

import java.util.ArrayList;
import java.util.List;

import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;
import rp3.marketforce.db.Contract;
import rp3.util.CursorUtils;

/**
 * Created by magno_000 on 15/05/2015.
 */
public class OportunidadTareaActividad extends EntityBase<OportunidadTareaActividad> {

    private long id;
    private int idOportunidad;
    private int _idOportunidad;
    private int idEtapa;
    private int idTarea;
    private int idTareaActividad;
    private String resultado;
    private String idsResultado;

    @Override
    public long getID() {
        return id;
    }

    @Override
    public void setID(long id) {
        this.id = id;
    }

    public int getIdOportunidad() {
        return idOportunidad;
    }

    public void setIdOportunidad(int idOportunidad) {
        this.idOportunidad = idOportunidad;
    }

    public int get_idOportunidad() {
        return _idOportunidad;
    }

    public void set_idOportunidad(int _idOportunidad) {
        this._idOportunidad = _idOportunidad;
    }

    public int getIdEtapa() {
        return idEtapa;
    }

    public void setIdEtapa(int idEtapa) {
        this.idEtapa = idEtapa;
    }

    public int getIdTarea() {
        return idTarea;
    }

    public void setIdTarea(int idTarea) {
        this.idTarea = idTarea;
    }

    public int getIdTareaActividad() {
        return idTareaActividad;
    }

    public void setIdTareaActividad(int idTareaActividad) {
        this.idTareaActividad = idTareaActividad;
    }

    public String getResultado() {
        return resultado;
    }

    public void setResultado(String resultado) {
        this.resultado = resultado;
    }

    public String getIdsResultado() {
        return idsResultado;
    }

    public void setIdsResultado(String idsResultado) {
        this.idsResultado = idsResultado;
    }

    @Override
    public boolean isAutoGeneratedId() {
        return true;
    }

    @Override
    public String getTableName() {
        return Contract.OportunidadTareaActividad.TABLE_NAME;
    }

    @Override
    public void setValues() {
        setValue(Contract.OportunidadTareaActividad.COLUMN_ID_ETAPA, this.idEtapa);
        setValue(Contract.OportunidadTareaActividad.COLUMN_ID_OPORTUNIDAD, this.idOportunidad);
        setValue(Contract.OportunidadTareaActividad.COLUMN_ID_OPORTUNIDAD_INT, this._idOportunidad);
        setValue(Contract.OportunidadTareaActividad.COLUMN_ID_TAREA, this.idTarea);
        setValue(Contract.OportunidadTareaActividad.COLUMN_TAREA_ACTIVIDAD_ID, this.idTareaActividad);
        setValue(Contract.OportunidadTareaActividad.COLUMN_RESULTADO, this.resultado);
        setValue(Contract.OportunidadTareaActividad.COLUMN_IDS_RESULTADO, this.idsResultado);
    }

    @Override
    public Object getValue(String key) {
        return null;
    }

    @Override
    public String getDescription() {
        return null;
    }

    public static List<OportunidadTareaActividad> getActividades(DataBase db, int idOportunidad, int idTarea, int idEtapa) {
        List<OportunidadTareaActividad> lista_actividades = new ArrayList<OportunidadTareaActividad>();

        Cursor c = db.query(Contract.OportunidadTareaActividad.TABLE_NAME,
                new String[] {Contract.OportunidadTareaActividad._ID, Contract.OportunidadTareaActividad.COLUMN_ID_ETAPA,
                        Contract.OportunidadTareaActividad.COLUMN_RESULTADO, Contract.OportunidadTareaActividad.COLUMN_ID_OPORTUNIDAD, Contract.OportunidadTareaActividad.COLUMN_IDS_RESULTADO,
                        Contract.OportunidadTareaActividad.COLUMN_TAREA_ACTIVIDAD_ID,
                        Contract.OportunidadTareaActividad.COLUMN_ID_TAREA,},
                Contract.OportunidadTareaActividad.COLUMN_ID_OPORTUNIDAD + " = ? AND " +
                        Contract.OportunidadTareaActividad.COLUMN_ID_ETAPA + " = ? AND " +
                        Contract.OportunidadTareaActividad.COLUMN_ID_TAREA + " = ?",
                new String[] {idOportunidad + "", idEtapa + "", idTarea + ""} );

        if(c.moveToFirst())
        {
            do
            {
                OportunidadTareaActividad actividad = new OportunidadTareaActividad();
                actividad.setID(CursorUtils.getLong(c, Contract.OportunidadTareaActividad._ID));
                actividad.setIdEtapa(CursorUtils.getInt(c, Contract.OportunidadTareaActividad.COLUMN_ID_ETAPA));
                actividad.setResultado(CursorUtils.getString(c, Contract.OportunidadTareaActividad.COLUMN_RESULTADO));
                actividad.setIdsResultado(CursorUtils.getString(c, Contract.OportunidadTareaActividad.COLUMN_IDS_RESULTADO));
                actividad.setIdOportunidad(CursorUtils.getInt(c, Contract.OportunidadTareaActividad.COLUMN_ID_OPORTUNIDAD));
                actividad.setIdTareaActividad(CursorUtils.getInt(c, Contract.OportunidadTareaActividad.COLUMN_TAREA_ACTIVIDAD_ID));
                actividad.setIdTarea(CursorUtils.getInt(c, Contract.OportunidadTareaActividad.COLUMN_ID_TAREA));
                lista_actividades.add(actividad);
            }while(c.moveToNext());
        }

        return lista_actividades;
    }

    public static List<OportunidadTareaActividad> getActividadesInt(DataBase db, long id, int idTarea, int idEtapa) {
        List<OportunidadTareaActividad> lista_actividades = new ArrayList<OportunidadTareaActividad>();

        Cursor c = db.query(Contract.OportunidadTareaActividad.TABLE_NAME,
                new String[] {Contract.OportunidadTareaActividad._ID, Contract.OportunidadTareaActividad.COLUMN_ID_ETAPA,
                        Contract.OportunidadTareaActividad.COLUMN_RESULTADO, Contract.OportunidadTareaActividad.COLUMN_ID_OPORTUNIDAD, Contract.OportunidadTareaActividad.COLUMN_IDS_RESULTADO,
                        Contract.OportunidadTareaActividad.COLUMN_TAREA_ACTIVIDAD_ID,
                        Contract.OportunidadTareaActividad.COLUMN_ID_TAREA,},
                Contract.OportunidadTareaActividad.COLUMN_ID_OPORTUNIDAD_INT + " = ? AND " +
                        Contract.OportunidadTareaActividad.COLUMN_ID_ETAPA + " = ? AND " +
                        Contract.OportunidadTareaActividad.COLUMN_ID_TAREA + " = ?",
                new String[] {id + "", idEtapa + "", idTarea + ""} );

        if(c.moveToFirst())
        {
            do
            {
                OportunidadTareaActividad actividad = new OportunidadTareaActividad();
                actividad.setID(CursorUtils.getLong(c, Contract.OportunidadTareaActividad._ID));
                actividad.setIdEtapa(CursorUtils.getInt(c, Contract.OportunidadTareaActividad.COLUMN_ID_ETAPA));
                actividad.setResultado(CursorUtils.getString(c, Contract.OportunidadTareaActividad.COLUMN_RESULTADO));
                actividad.setIdsResultado(CursorUtils.getString(c, Contract.OportunidadTareaActividad.COLUMN_IDS_RESULTADO));
                actividad.setIdOportunidad(CursorUtils.getInt(c, Contract.OportunidadTareaActividad.COLUMN_ID_OPORTUNIDAD));
                actividad.setIdTareaActividad(CursorUtils.getInt(c, Contract.OportunidadTareaActividad.COLUMN_TAREA_ACTIVIDAD_ID));
                actividad.setIdTarea(CursorUtils.getInt(c, Contract.OportunidadTareaActividad.COLUMN_ID_TAREA));
                lista_actividades.add(actividad);
            }while(c.moveToNext());
        }

        return lista_actividades;
    }

    public static OportunidadTareaActividad getActividadSimple(DataBase db, int id_etapa, int id_oportunidad, int id_actividad, int idTareaActividad) {
        Cursor c = db.query(Contract.OportunidadTareaActividad.TABLE_NAME,
                new String[] {Contract.OportunidadTareaActividad._ID, Contract.OportunidadTareaActividad.COLUMN_ID_ETAPA,
                        Contract.OportunidadTareaActividad.COLUMN_RESULTADO, Contract.OportunidadTareaActividad.COLUMN_ID_OPORTUNIDAD, Contract.OportunidadTareaActividad.COLUMN_IDS_RESULTADO,
                        Contract.OportunidadTareaActividad.COLUMN_TAREA_ACTIVIDAD_ID,
                        Contract.OportunidadTareaActividad.COLUMN_ID_TAREA,},
                Contract.OportunidadTareaActividad.COLUMN_ID_OPORTUNIDAD + " = ? AND " +
                        Contract.OportunidadTareaActividad.COLUMN_ID_ETAPA + " = ? AND " +
                        Contract.OportunidadTareaActividad.COLUMN_ID_TAREA + " = ? AND " +
                        Contract.OportunidadTareaActividad.COLUMN_TAREA_ACTIVIDAD_ID + " = ?",
                new String[] {id_oportunidad + "", id_etapa + "", id_actividad + "", idTareaActividad+ ""} );

        OportunidadTareaActividad actividad = null;

        if(c.moveToFirst())
        {
            actividad = new OportunidadTareaActividad();
                actividad.setID(CursorUtils.getLong(c, Contract.OportunidadTareaActividad._ID));
                actividad.setIdEtapa(CursorUtils.getInt(c, Contract.OportunidadTareaActividad.COLUMN_ID_ETAPA));
                actividad.setResultado(CursorUtils.getString(c, Contract.OportunidadTareaActividad.COLUMN_RESULTADO));
                actividad.setIdsResultado(CursorUtils.getString(c, Contract.OportunidadTareaActividad.COLUMN_IDS_RESULTADO));
                actividad.setIdOportunidad(CursorUtils.getInt(c, Contract.OportunidadTareaActividad.COLUMN_ID_OPORTUNIDAD));
                actividad.setIdTareaActividad(CursorUtils.getInt(c, Contract.OportunidadTareaActividad.COLUMN_TAREA_ACTIVIDAD_ID));
                actividad.setIdTarea(CursorUtils.getInt(c, Contract.OportunidadTareaActividad.COLUMN_ID_TAREA));
        }

        return actividad;

    }
}
