package rp3.marketforce.models.oportunidad;

import java.util.Date;

import rp3.data.entity.EntityBase;
import rp3.marketforce.db.Contract;

/**
 * Created by magno_000 on 07/09/2015.
 */
public class OportunidadBitacora extends EntityBase<OportunidadBitacora> {

    private long id;
    private int idOportunidad;
    private int _idOportunidad;
    private int idOportunidadBitacora;
    private int idAgente;
    private String detalle;
    private Date fecha;

    @Override
    public long getID() {
        return id;
    }

    @Override
    public void setID(long id) {
        this.id = id;
    }

    public int getIdOportunidad() {
        return idOportunidad;
    }

    public void setIdOportunidad(int idOportunidad) {
        this.idOportunidad = idOportunidad;
    }

    public int get_idOportunidad() {
        return _idOportunidad;
    }

    public void set_idOportunidad(int _idOportunidad) {
        this._idOportunidad = _idOportunidad;
    }

    public int getIdOportunidadBitacora() {
        return idOportunidadBitacora;
    }

    public void setIdOportunidadBitacora(int idOportunidadBitacora) {
        this.idOportunidadBitacora = idOportunidadBitacora;
    }

    public int getIdAgente() {
        return idAgente;
    }

    public void setIdAgente(int idAgente) {
        this.idAgente = idAgente;
    }

    public String getDetalle() {
        return detalle;
    }

    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Override
    public boolean isAutoGeneratedId() {
        return true;
    }

    @Override
    public String getTableName() {
        return Contract.OportunidadBitacora.TABLE_NAME;
    }

    @Override
    public void setValues() {
        setValue(Contract.OportunidadBitacora.COLUMN_ID_AGENTE, this.idAgente);
        setValue(Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD, this.idOportunidad);
        setValue(Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_INT, this._idOportunidad);
        setValue(Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_BITACORA, this.idOportunidadBitacora);
        setValue(Contract.OportunidadBitacora.COLUMN_DETALLE, this.detalle);
        setValue(Contract.OportunidadBitacora.COLUMN_FECHA, this.fecha);
    }

    @Override
    public Object getValue(String key) {
        return null;
    }

    @Override
    public String getDescription() {
        return null;
    }


}
