package rp3.marketforce.models.oportunidad;

import android.database.Cursor;

import java.util.ArrayList;
import java.util.List;

import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;
import rp3.marketforce.db.Contract;
import rp3.util.CursorUtils;

/**
 * Created by magno_000 on 14/05/2015.
 */
public class OportunidadContacto extends EntityBase<OportunidadContacto> {

    private long id;
    private int idOportunidadContacto;
    private int idOportunidad;
    private int _idOportunidad;
    private String nombre;
    private boolean esPrincipal;
    private String movil;
    private String fijo;
    private String email;
    private String cargo;
    private String URLFoto;

    @Override
    public long getID() {
        return id;
    }

    @Override
    public void setID(long id) {
        this.id = id;
    }

    public int getIdOportunidadContacto() {
        return idOportunidadContacto;
    }

    public void setIdOportunidadContacto(int idOportunidadContacto) {
        this.idOportunidadContacto = idOportunidadContacto;
    }

    public int getIdOportunidad() {
        return idOportunidad;
    }

    public void setIdOportunidad(int idOportunidad) {
        this.idOportunidad = idOportunidad;
    }

    public int get_idOportunidad() {
        return _idOportunidad;
    }

    public void set_idOportunidad(int _idOportunidad) {
        this._idOportunidad = _idOportunidad;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public boolean isEsPrincipal() {
        return esPrincipal;
    }

    public void setEsPrincipal(boolean esPrincipal) {
        this.esPrincipal = esPrincipal;
    }

    public String getMovil() {
        return movil;
    }

    public void setMovil(String movil) {
        this.movil = movil;
    }

    public String getFijo() {
        return fijo;
    }

    public void setFijo(String fijo) {
        this.fijo = fijo;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getCargo() {
        return cargo;
    }

    public void setCargo(String cargo) {
        this.cargo = cargo;
    }

    public String getURLFoto() {
        return URLFoto;
    }

    public void setURLFoto(String URLFoto) {
        this.URLFoto = URLFoto;
    }

    @Override
    public boolean isAutoGeneratedId() {
        return true;
    }

    @Override
    public String getTableName() {
        return Contract.OportunidadContacto.TABLE_NAME;
    }

    @Override
    public void setValues() {
        setValue(Contract.OportunidadContacto.COLUMN_ID_OPORTUNIDAD, this.idOportunidad);
        setValue(Contract.OportunidadContacto.COLUMN_NOMBRE, this.nombre);
        setValue(Contract.OportunidadContacto.COLUMN_ID_OPORTUNIDAD_CONTACTO, this.idOportunidadContacto);
        setValue(Contract.OportunidadContacto.COLUMN_ID_OPORTUNIDAD_INT, this._idOportunidad);
        setValue(Contract.OportunidadContacto.COLUMN_CARGO, this.cargo);
        setValue(Contract.OportunidadContacto.COLUMN_URL_FOTO, this.URLFoto);
    }

    @Override
    public Object getValue(String key) {
        return null;
    }

    @Override
    public String getDescription() {
        return null;
    }

    public static List<OportunidadContacto> getContactosOportunidad(DataBase db, int idOportunidad) {
        Cursor c = db.query(Contract.OportunidadContacto.TABLE_NAME, new String[] {Contract.OportunidadContacto._ID, Contract.OportunidadContacto.COLUMN_ID_OPORTUNIDAD,
                Contract.OportunidadContacto.COLUMN_NOMBRE, Contract.OportunidadContacto.COLUMN_ID_OPORTUNIDAD_CONTACTO, Contract.OportunidadContacto.COLUMN_CARGO,
                Contract.OportunidadContacto.COLUMN_URL_FOTO}, Contract.OportunidadContacto.COLUMN_ID_OPORTUNIDAD + " = ?",
                new String[] {idOportunidad + ""});

        List<OportunidadContacto> list = new ArrayList<OportunidadContacto>();
        while(c.moveToNext()){
            OportunidadContacto cont = new OportunidadContacto();
            cont.setID(CursorUtils.getInt(c, Contract.OportunidadContacto._ID));
            cont.setIdOportunidad(CursorUtils.getInt(c, Contract.OportunidadContacto.COLUMN_ID_OPORTUNIDAD));
            cont.setNombre(CursorUtils.getString(c, Contract.OportunidadContacto.COLUMN_NOMBRE));
            cont.setIdOportunidadContacto(CursorUtils.getInt(c, Contract.OportunidadContacto.COLUMN_ID_OPORTUNIDAD_CONTACTO));
            cont.setCargo(CursorUtils.getString(c, Contract.OportunidadContacto.COLUMN_CARGO));
            cont.setURLFoto(CursorUtils.getString(c, Contract.OportunidadContacto.COLUMN_URL_FOTO));
            list.add(cont);
        }
        return list;
    }

    public static List<OportunidadContacto> getContactosOportunidadInt(DataBase db, long id) {
        Cursor c = db.query(Contract.OportunidadContacto.TABLE_NAME, new String[] {Contract.OportunidadContacto._ID, Contract.OportunidadContacto.COLUMN_ID_OPORTUNIDAD,
                        Contract.OportunidadContacto.COLUMN_NOMBRE, Contract.OportunidadContacto.COLUMN_ID_OPORTUNIDAD_CONTACTO, Contract.OportunidadContacto.COLUMN_CARGO,
                        Contract.OportunidadContacto.COLUMN_URL_FOTO}, Contract.OportunidadContacto.COLUMN_ID_OPORTUNIDAD_INT + " = ?",
                new String[] {id + ""});

        List<OportunidadContacto> list = new ArrayList<OportunidadContacto>();
        while(c.moveToNext()){
            OportunidadContacto cont = new OportunidadContacto();
            cont.setID(CursorUtils.getInt(c, Contract.OportunidadContacto._ID));
            cont.setIdOportunidad(CursorUtils.getInt(c, Contract.OportunidadContacto.COLUMN_ID_OPORTUNIDAD));
            cont.setNombre(CursorUtils.getString(c, Contract.OportunidadContacto.COLUMN_NOMBRE));
            cont.setIdOportunidadContacto(CursorUtils.getInt(c, Contract.OportunidadContacto.COLUMN_ID_OPORTUNIDAD_CONTACTO));
            cont.setCargo(CursorUtils.getString(c, Contract.OportunidadContacto.COLUMN_CARGO));
            cont.setURLFoto(CursorUtils.getString(c, Contract.OportunidadContacto.COLUMN_URL_FOTO));
            list.add(cont);
        }
        return list;
    }
}
