package rp3.berlin.models.oportunidad;

import android.database.Cursor;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;
import rp3.berlin.db.Contract;
import rp3.berlin.models.Agente;
import rp3.util.CursorUtils;

/**
 * Created by magno_000 on 07/09/2015.
 */
public class OportunidadBitacora extends EntityBase<OportunidadBitacora> {

    private long id;
    private int idOportunidad;
    private int _idOportunidad;
    private int idOportunidadBitacora;
    private int idAgente;
    private String detalle;
    private Date fecha;
    private int idAgenda;

    private Agente agente;

    @Override
    public long getID() {
        return id;
    }

    @Override
    public void setID(long id) {
        this.id = id;
    }

    public int getIdOportunidad() {
        return idOportunidad;
    }

    public void setIdOportunidad(int idOportunidad) {
        this.idOportunidad = idOportunidad;
    }

    public int get_idOportunidad() {
        return _idOportunidad;
    }

    public void set_idOportunidad(int _idOportunidad) {
        this._idOportunidad = _idOportunidad;
    }

    public int getIdOportunidadBitacora() {
        return idOportunidadBitacora;
    }

    public void setIdOportunidadBitacora(int idOportunidadBitacora) {
        this.idOportunidadBitacora = idOportunidadBitacora;
    }

    public int getIdAgente() {
        return idAgente;
    }

    public void setIdAgente(int idAgente) {
        this.idAgente = idAgente;
    }

    public String getDetalle() {
        return detalle;
    }

    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public int getIdAgenda() {
        return idAgenda;
    }

    public void setIdAgenda(int idAgenda) {
        this.idAgenda = idAgenda;
    }

    public Agente getAgente() {
        return agente;
    }

    public void setAgente(Agente agente) {
        this.agente = agente;
    }

    @Override
    public boolean isAutoGeneratedId() {
        return true;
    }

    @Override
    public String getTableName() {
        return Contract.OportunidadBitacora.TABLE_NAME;
    }

    @Override
    public void setValues() {
        setValue(Contract.OportunidadBitacora.COLUMN_ID_AGENTE, this.idAgente);
        setValue(Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD, this.idOportunidad);
        setValue(Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_INT, this._idOportunidad);
        setValue(Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_BITACORA, this.idOportunidadBitacora);
        setValue(Contract.OportunidadBitacora.COLUMN_DETALLE, this.detalle);
        setValue(Contract.OportunidadBitacora.COLUMN_FECHA, this.fecha);
        setValue(Contract.OportunidadBitacora.COLUMN_ID_AGENDA, this.idAgenda);
    }

    @Override
    public Object getValue(String key) {
        return null;
    }

    @Override
    public String getDescription() {
        return null;
    }


    public static List<OportunidadBitacora> getBitacoraOportunidad(DataBase db, int idOportunidad) {
        Cursor c = db.query(Contract.OportunidadBitacora.TABLE_NAME,new String[] {Contract.OportunidadBitacora._ID, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD,
                Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_INT, Contract.OportunidadBitacora.COLUMN_ID_AGENTE, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_BITACORA,
                Contract.OportunidadBitacora.COLUMN_DETALLE, Contract.OportunidadBitacora.COLUMN_FECHA, Contract.OportunidadBitacora.COLUMN_ID_AGENDA}, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD + " = ? "
                , new String[]{idOportunidad + ""}, null, null, Contract.OportunidadBitacora.COLUMN_FECHA + " DESC");

        List<OportunidadBitacora> list = new ArrayList<OportunidadBitacora>();
        while(c.moveToNext()){
            OportunidadBitacora cont = new OportunidadBitacora();
            cont.setID(CursorUtils.getInt(c, Contract.OportunidadBitacora._ID));
            cont.setIdOportunidad(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD));
            cont.setIdAgente(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_AGENTE));
            cont.setIdOportunidadBitacora(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_BITACORA));
            cont.set_idOportunidad(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_INT));
            cont.setDetalle(CursorUtils.getString(c, Contract.OportunidadBitacora.COLUMN_DETALLE));
            cont.setFecha(CursorUtils.getDate(c, Contract.OportunidadBitacora.COLUMN_FECHA));
            cont.setIdAgenda(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_AGENDA));
            cont.setAgente(Agente.getAgente(db, cont.getIdAgente()));
            list.add(cont);
        }
        c.close();
        return list;
    }

    public static OportunidadBitacora getBitacoraOportunidadUnit(DataBase db, int idOportunidad, int idBitacora) {
        Cursor c = db.query(Contract.OportunidadBitacora.TABLE_NAME,new String[] {Contract.OportunidadBitacora._ID, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD,
                Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_INT, Contract.OportunidadBitacora.COLUMN_ID_AGENTE, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_BITACORA,
                Contract.OportunidadBitacora.COLUMN_DETALLE, Contract.OportunidadBitacora.COLUMN_FECHA, Contract.OportunidadBitacora.COLUMN_ID_AGENDA}, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD + " = ? AND "
                + Contract.OportunidadBitacora._ID + " = ? "
                , new String[]{idOportunidad + "", idBitacora + ""});

        OportunidadBitacora resp = new OportunidadBitacora();
        if(c.moveToFirst()){
            resp.setID(CursorUtils.getInt(c, Contract.OportunidadBitacora._ID));
            resp.setIdOportunidad(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD));
            resp.setIdAgente(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_AGENTE));
            resp.setIdOportunidadBitacora(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_BITACORA));
            resp.set_idOportunidad(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_INT));
            resp.setDetalle(CursorUtils.getString(c, Contract.OportunidadBitacora.COLUMN_DETALLE));
            resp.setFecha(CursorUtils.getDate(c, Contract.OportunidadBitacora.COLUMN_FECHA));
            resp.setIdAgenda(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_AGENDA));
            resp.setAgente(Agente.getAgente(db, resp.getIdAgente()));
        }
        c.close();
        return resp;
    }

    public static OportunidadBitacora getBitacoraOportunidadUnitInt(DataBase db, long idOportunidad, int idBitacora) {
        Cursor c = db.query(Contract.OportunidadBitacora.TABLE_NAME,new String[] {Contract.OportunidadBitacora._ID, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD,
                Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_INT, Contract.OportunidadBitacora.COLUMN_ID_AGENTE, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_BITACORA,
                Contract.OportunidadBitacora.COLUMN_DETALLE, Contract.OportunidadBitacora.COLUMN_FECHA, Contract.OportunidadBitacora.COLUMN_ID_AGENDA}, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_INT + " = ? AND "
                + Contract.OportunidadBitacora._ID + " = ? "
                , new String[]{idOportunidad + "", idBitacora + ""});

        OportunidadBitacora resp = new OportunidadBitacora();
        if(c.moveToFirst()){
            resp.setID(CursorUtils.getInt(c, Contract.OportunidadBitacora._ID));
            resp.setIdOportunidad(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD));
            resp.setIdAgente(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_AGENTE));
            resp.setIdOportunidadBitacora(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_BITACORA));
            resp.set_idOportunidad(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_INT));
            resp.setDetalle(CursorUtils.getString(c, Contract.OportunidadBitacora.COLUMN_DETALLE));
            resp.setFecha(CursorUtils.getDate(c, Contract.OportunidadBitacora.COLUMN_FECHA));
            resp.setIdAgenda(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_AGENDA));
            resp.setAgente(Agente.getAgente(db, resp.getIdAgente()));
        }
        c.close();
        return resp;
    }

    public static List<OportunidadBitacora> getBitacoraOportunidadInt(DataBase db, long idOportunidad) {
        Cursor c = db.query(Contract.OportunidadBitacora.TABLE_NAME,new String[] {Contract.OportunidadBitacora._ID, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD,
                Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_INT, Contract.OportunidadBitacora.COLUMN_ID_AGENTE, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_BITACORA,
                Contract.OportunidadBitacora.COLUMN_DETALLE, Contract.OportunidadBitacora.COLUMN_FECHA, Contract.OportunidadBitacora.COLUMN_ID_AGENDA}, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_INT + " = ? "
                , new String[]{idOportunidad + ""}, null, null, Contract.OportunidadBitacora.COLUMN_FECHA + " DESC");

        List<OportunidadBitacora> list = new ArrayList<OportunidadBitacora>();
        while(c.moveToNext()){
            OportunidadBitacora cont = new OportunidadBitacora();
            cont.setID(CursorUtils.getInt(c, Contract.OportunidadBitacora._ID));
            cont.setIdOportunidad(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD));
            cont.setIdAgente(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_AGENTE));
            cont.setIdOportunidadBitacora(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_BITACORA));
            cont.set_idOportunidad(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_INT));
            cont.setDetalle(CursorUtils.getString(c, Contract.OportunidadBitacora.COLUMN_DETALLE));
            cont.setFecha(CursorUtils.getDate(c, Contract.OportunidadBitacora.COLUMN_FECHA));
            cont.setIdAgenda(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_AGENDA));
            cont.setAgente(Agente.getAgente(db, cont.getIdAgente()));
            list.add(cont);
        }
        c.close();
        return list;
    }

    public static List<OportunidadBitacora> getBitacoraOportunidadByAgenda(DataBase db, long idAgenda) {
        Cursor c = db.query(Contract.OportunidadBitacora.TABLE_NAME,new String[] {Contract.OportunidadBitacora._ID, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD,
                Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_INT, Contract.OportunidadBitacora.COLUMN_ID_AGENTE, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_BITACORA,
                Contract.OportunidadBitacora.COLUMN_DETALLE, Contract.OportunidadBitacora.COLUMN_FECHA, Contract.OportunidadBitacora.COLUMN_ID_AGENDA}, Contract.OportunidadBitacora.COLUMN_ID_AGENDA + " = ? "
                , new String[]{idAgenda + ""}, null, null, Contract.OportunidadBitacora.COLUMN_FECHA + " DESC");

        List<OportunidadBitacora> list = new ArrayList<OportunidadBitacora>();
        while(c.moveToNext()){
            OportunidadBitacora cont = new OportunidadBitacora();
            cont.setID(CursorUtils.getInt(c, Contract.OportunidadBitacora._ID));
            cont.setIdOportunidad(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD));
            cont.setIdAgente(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_AGENTE));
            cont.setIdOportunidadBitacora(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_BITACORA));
            cont.set_idOportunidad(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_OPORTUNIDAD_INT));
            cont.setDetalle(CursorUtils.getString(c, Contract.OportunidadBitacora.COLUMN_DETALLE));
            cont.setFecha(CursorUtils.getDate(c, Contract.OportunidadBitacora.COLUMN_FECHA));
            cont.setIdAgenda(CursorUtils.getInt(c, Contract.OportunidadBitacora.COLUMN_ID_AGENDA));
            cont.setAgente(Agente.getAgente(db, cont.getIdAgente()));
            list.add(cont);
        }
        c.close();
        return list;
    }
}
