package rp3.marketforce.models.pedido;

import android.database.Cursor;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;
import rp3.marketforce.db.Contract;
import rp3.util.CursorUtils;

/**
 * Created by magno_000 on 12/04/2017.
 */

public class Alternativo extends EntityBase<Alternativo> {

    private long id;
    private String item;
    private String alterno;
    private Date fechaIngreso;
    private Date fechaVencimiento;

    @Override
    public long getID() {
        return id;
    }

    @Override
    public void setID(long id) {
        this.id = id;
    }

    @Override
    public boolean isAutoGeneratedId() {
        return true;
    }

    @Override
    public String getTableName() {
        return Contract.Alternativo.TABLE_NAME;
    }

    @Override
    public void setValues() {
        setValue(Contract.Alternativo.COLUMN_ITEM, this.item);
        setValue(Contract.Alternativo.COLUMN_ALTERNO, this.alterno);
        setValue(Contract.Alternativo.COLUMN_FECHA_INGRESO, this.fechaIngreso);
        setValue(Contract.Alternativo.COLUMN_FECHA_VENCIMIENTO, this.fechaVencimiento);
    }

    @Override
    public Object getValue(String key) {
        return item;
    }

    @Override
    public String getDescription() {
        return alterno;
    }

    public String getItem() {
        return item;
    }

    public void setItem(String item) {
        this.item = item;
    }

    public String getAlterno() {
        return alterno;
    }

    public void setAlterno(String alterno) {
        this.alterno = alterno;
    }

    public Date getFechaIngreso() {
        return fechaIngreso;
    }

    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    public Date getFechaVencimiento() {
        return fechaVencimiento;
    }

    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }

    public static List<Alternativo> getAlterno(DataBase db, String item) {
        Cursor c = db.query(Contract.Alternativo.TABLE_NAME, new String[] {Contract.Alternativo._ID, Contract.Alternativo.COLUMN_ITEM, Contract.Alternativo.COLUMN_ALTERNO}
                , Contract.Alternativo.COLUMN_ITEM + " = ?" , new String[] {item + ""});

        List<Alternativo> list = new ArrayList<Alternativo>();
        while(c.moveToNext()){
            Alternativo alterno = new Alternativo();
            alterno.setID(CursorUtils.getInt(c, Contract.Alternativo._ID));
            alterno.setItem(CursorUtils.getString(c, Contract.Alternativo.COLUMN_ITEM));
            alterno.setAlterno(CursorUtils.getString(c, Contract.Alternativo.COLUMN_ALTERNO));
            list.add(alterno);
        }
        c.close();
        return list;
    }
}
