package rp3.marketforce.models.pedido;

import android.database.Cursor;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;
import rp3.marketforce.db.Contract;
import rp3.marketforce.models.Cliente;
import rp3.util.CursorUtils;

/**
 * Created by magno_000 on 04/11/2015.
 */
public class Categoria extends EntityBase<Categoria> {

    private long id;
    private int idCategoria;
    private String descripcion;

    @Override
    public long getID() {
        return id;
    }

    @Override
    public void setID(long id) {
        this.id = id;
    }

    @Override
    public boolean isAutoGeneratedId() {
        return true;
    }

    @Override
    public String getTableName() {
        return Contract.Categoria.TABLE_NAME;
    }

    public int getIdCategoria() {
        return idCategoria;
    }

    public void setIdCategoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Override
    public void setValues() {
        setValue(Contract.Categoria.COLUMN_ID_CATEGORIA, this.idCategoria);
        setValue(Contract.Categoria.COLUMN_DESCRIPCION, this.descripcion);
    }

    @Override
    public Object getValue(String key) {
        return null;
    }

    @Override
    public String getDescription() {
        return null;
    }

    public static List<Categoria> getCategorias(DataBase db) {
        Cursor c = db.query(Contract.Categoria.TABLE_NAME, new String[] {Contract.Categoria._ID, Contract.Categoria.COLUMN_ID_CATEGORIA, Contract.Categoria.COLUMN_DESCRIPCION});

        List<Categoria> list = new ArrayList<Categoria>();
        while(c.moveToNext()){
            Categoria categoria = new Categoria();
            categoria.setID(CursorUtils.getInt(c, Contract.Categoria._ID));
            categoria.setIdCategoria(CursorUtils.getInt(c, Contract.Categoria.COLUMN_ID_CATEGORIA));
            categoria.setDescripcion(CursorUtils.getString(c, Contract.Categoria.COLUMN_DESCRIPCION));
            list.add(categoria);
        }
        c.close();
        return list;
    }

    public static Categoria getCategoria(DataBase db, int idCategoria) {
        Cursor c = db.query(Contract.Categoria.TABLE_NAME, new String[] {Contract.Categoria._ID, Contract.Categoria.COLUMN_ID_CATEGORIA, Contract.Categoria.COLUMN_DESCRIPCION},
                Contract.Categoria.COLUMN_ID_CATEGORIA + " = ? ", new String[] {idCategoria + ""});

        Categoria categoria = new Categoria();
        while(c.moveToNext()){

            categoria.setID(CursorUtils.getInt(c, Contract.Categoria._ID));
            categoria.setIdCategoria(CursorUtils.getInt(c, Contract.Categoria.COLUMN_ID_CATEGORIA));
            categoria.setDescripcion(CursorUtils.getString(c, Contract.Categoria.COLUMN_DESCRIPCION));
        }
        c.close();
        return categoria;
    }

}
