package rp3.marketforce.models.pedido;

import java.util.Date;

import rp3.data.entity.EntityBase;
import rp3.marketforce.db.Contract;

/**
 * Created by magno_000 on 06/04/2017.
 */

public class LibroPrecio extends EntityBase<LibroPrecio> {

    private long id;
    private String idLibro;
    private String item;
    private String divisa;
    private double precio;
    private String medida;
    private Date fechaEfectiva;
    private Date fechaVencimiento;


    @Override
    public long getID() {
        return id;
    }

    @Override
    public void setID(long id) {
        this.id = id;
    }

    @Override
    public boolean isAutoGeneratedId() {
        return true;
    }

    @Override
    public String getTableName() {
        return Contract.LibroPrecio.TABLE_NAME;
    }

    public String getIdLibro() {
        return idLibro;
    }

    public void setIdLibro(String idLibro) {
        this.idLibro = idLibro;
    }

    public String getItem() {
        return item;
    }

    public void setItem(String item) {
        this.item = item;
    }

    public String getDivisa() {
        return divisa;
    }

    public void setDivisa(String divisa) {
        this.divisa = divisa;
    }

    public double getPrecio() {
        return precio;
    }

    public void setPrecio(double precio) {
        this.precio = precio;
    }

    public String getMedida() {
        return medida;
    }

    public void setMedida(String medida) {
        this.medida = medida;
    }

    public Date getFechaEfectiva() {
        return fechaEfectiva;
    }

    public void setFechaEfectiva(Date fechaEfectiva) {
        this.fechaEfectiva = fechaEfectiva;
    }

    public Date getFechaVencimiento() {
        return fechaVencimiento;
    }

    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }

    @Override
    public void setValues() {
        setValue(Contract.LibroPrecio.COLUMN_FECHA_EFECTIVA, this.fechaEfectiva);
        setValue(Contract.LibroPrecio.COLUMN_FECHA_VENCIMIENTO, this.fechaVencimiento);
        setValue(Contract.LibroPrecio.COLUMN_DIVISA, this.divisa);
        setValue(Contract.LibroPrecio.COLUMN_ID_LIBRO, this.idLibro);
        setValue(Contract.LibroPrecio.COLUMN_ITEM, this.item);
        setValue(Contract.LibroPrecio.COLUMN_MEDIDA, this.medida);
        setValue(Contract.LibroPrecio.COLUMN_PRECIO, this.precio);
    }

    @Override
    public Object getValue(String key) {
        return id;
    }

    @Override
    public String getDescription() {
        return item;
    }

    /*public static List<Banco> getBancos(DataBase db) {
        Cursor c = db.query(Contract.Banco.TABLE_NAME, new String[] {Contract.Banco._ID, Contract.Banco.COLUMN_ID_BANCO, Contract.Banco.COLUMN_DESCRIPCION});

        List<Banco> list = new ArrayList<Banco>();
        while(c.moveToNext()){
            Banco banco = new Banco();
            banco.setID(CursorUtils.getInt(c, Contract.Banco._ID));
            banco.setIdBanco(CursorUtils.getInt(c, Contract.Banco.COLUMN_ID_BANCO));
            banco.setDescripcion(CursorUtils.getString(c, Contract.Banco.COLUMN_DESCRIPCION));
            list.add(banco);
        }
        c.close();
        return list;
    }*/
}
