package rp3.marketforce.models.pedido;

import java.util.Date;

import rp3.data.entity.EntityBase;
import rp3.marketforce.db.Contract;

/**
 * Created by magno_000 on 06/04/2017.
 */

public class MatrizPrecio extends EntityBase<MatrizPrecio> {

    private long id;
    private String idMatriz;
    private String idLibro;
    private String idCliente;
    private int secuencia;
    private String idListaPrecio;
    private int parametroDesc;
    private Date fechaEfectiva;
    private Date fechaVencimiento;

    @Override
    public long getID() {
        return id;
    }

    @Override
    public void setID(long id) {
        this.id = id;
    }

    @Override
    public boolean isAutoGeneratedId() {
        return true;
    }

    @Override
    public String getTableName() {
        return Contract.MatrizPrecio.TABLE_NAME;
    }

    public String getIdMatriz() {
        return idMatriz;
    }

    public void setIdMatriz(String idMatriz) {
        this.idMatriz = idMatriz;
    }

    public int getParametroDesc() {
        return parametroDesc;
    }

    public void setParametroDesc(int parametroDesc) {
        this.parametroDesc = parametroDesc;
    }

    public Date getFechaEfectiva() {
        return fechaEfectiva;
    }

    public void setFechaEfectiva(Date fechaEfectiva) {
        this.fechaEfectiva = fechaEfectiva;
    }

    public Date getFechaVencimiento() {
        return fechaVencimiento;
    }

    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }

    public String getIdLibro() {
        return idLibro;
    }

    public void setIdLibro(String idLibro) {
        this.idLibro = idLibro;
    }

    public String getIdCliente() {
        return idCliente;
    }

    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }

    public int getSecuencia() {
        return secuencia;
    }

    public void setSecuencia(int secuencia) {
        this.secuencia = secuencia;
    }

    public String getIdListaPrecio() {
        return idListaPrecio;
    }

    public void setIdListaPrecio(String idListaPrecio) {
        this.idListaPrecio = idListaPrecio;
    }

    @Override
    public void setValues() {
        setValue(Contract.MatrizPrecio.COLUMN_FECHA_EFECTIVA, this.fechaEfectiva);
        setValue(Contract.MatrizPrecio.COLUMN_FECHA_VENCIMIENTO, this.fechaVencimiento);
        setValue(Contract.MatrizPrecio.COLUMN_ID_CLIENTE, this.idCliente);
        setValue(Contract.MatrizPrecio.COLUMN_ID_LIBRO, this.idLibro);
        setValue(Contract.MatrizPrecio.COLUMN_ID_LISTA_PRECIO, this.idListaPrecio);
        setValue(Contract.MatrizPrecio.COLUMN_ID_MATRIZ, this.idMatriz);
        setValue(Contract.MatrizPrecio.COLUMN_ID_SECUENCIA, this.secuencia);
        setValue(Contract.MatrizPrecio.COLUMN_PARAMETRO_DESC, this.parametroDesc);
    }

    @Override
    public Object getValue(String key) {
        return id;
    }

    @Override
    public String getDescription() {
        return idMatriz;
    }

    /*public static List<Banco> getBancos(DataBase db) {
        Cursor c = db.query(Contract.Banco.TABLE_NAME, new String[] {Contract.Banco._ID, Contract.Banco.COLUMN_ID_BANCO, Contract.Banco.COLUMN_DESCRIPCION});

        List<Banco> list = new ArrayList<Banco>();
        while(c.moveToNext()){
            Banco banco = new Banco();
            banco.setID(CursorUtils.getInt(c, Contract.Banco._ID));
            banco.setIdBanco(CursorUtils.getInt(c, Contract.Banco.COLUMN_ID_BANCO));
            banco.setDescripcion(CursorUtils.getString(c, Contract.Banco.COLUMN_DESCRIPCION));
            list.add(banco);
        }
        c.close();
        return list;
    }*/
}
