package rp3.marketforce.models.pedido;

import android.database.Cursor;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;
import rp3.marketforce.Contants;
import rp3.marketforce.db.Contract;
import rp3.util.CursorUtils;

/**
 * Created by magno_000 on 12/10/2015.
 */
public class PedidoDetalle extends EntityBase<PedidoDetalle> {

    private long id;
    private int idPedidoDetalle;
    private int idPedido;
    private int _idPedido;
    private int idProducto;
    private String descripcion;
    private double valorUnitario;
    private int cantidad;
    private double valorTotal;
    private String urlFoto;
    private double subtotal;
    private double subtotalSinDescuento;
    private double subtotalSinImpuesto;
    private double baseImponible;
    private double baseImponibleCero;
    private double porcentajeDescuentoOro;
    private double valorDescuentoOro;
    private double valorDescuentoOroTotal;
    private double porcentajeDescuentoManual;
    private double valorDescuentoManual;
    private double valorDescuentoManualTotal;
    private double porcentajeDescuentoAutomatico;
    private double valorDescuentoAutomatico;
    private double valorDescuentoAutomaticoTotal;
    private double porcentajeImpuesto;
    private double valorImpuesto;
    private double valorImpuestoTotal;
    private int cantidadDevolucion;
    private double baseICE;

    private Producto producto;
    private String codigoExterno;


    @Override
    public long getID() {
        return id;
    }

    @Override
    public void setID(long id) {
        this.id = id;
    }

    @Override
    public boolean isAutoGeneratedId() {
        return true;
    }

    @Override
    public String getTableName() {
        return Contract.PedidoDetalle.TABLE_NAME;
    }

    public int getIdPedido() {
        return idPedido;
    }

    public void setIdPedido(int idPedido) {
        this.idPedido = idPedido;
    }

    public int getIdPedidoDetalle() {
        return idPedidoDetalle;
    }

    public void setIdPedidoDetalle(int idPedidoDetalle) {
        this.idPedidoDetalle = idPedidoDetalle;
    }

    public int get_idPedido() {
        return _idPedido;
    }

    public void set_idPedido(int _idPedido) {
        this._idPedido = _idPedido;
    }

    public int getIdProducto() {
        return idProducto;
    }

    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public double getValorUnitario() {
        return valorUnitario;
    }

    public void setValorUnitario(double valorUnitario) {
        this.valorUnitario = valorUnitario;
    }

    public int getCantidad() {
        return cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    public double getValorTotal() {
        return valorTotal;
    }

    public void setValorTotal(double valorTotal) {
        this.valorTotal = valorTotal;
    }

    public String getUrlFoto() {
        return urlFoto;
    }

    public void setUrlFoto(String urlFoto) {
        this.urlFoto = urlFoto;
    }

    public double getSubtotal() {
        return subtotal;
    }

    public void setSubtotal(double subtotal) {
        this.subtotal = subtotal;
    }

    public double getSubtotalSinDescuento() {
        return subtotalSinDescuento;
    }

    public void setSubtotalSinDescuento(double subtotalSinDescuento) {
        this.subtotalSinDescuento = subtotalSinDescuento;
    }

    public double getPorcentajeDescuentoOro() {
        return porcentajeDescuentoOro;
    }

    public void setPorcentajeDescuentoOro(double porcentajeDescuentoOro) {
        this.porcentajeDescuentoOro = porcentajeDescuentoOro;
    }

    public double getValorDescuentoOro() {
        return valorDescuentoOro;
    }

    public void setValorDescuentoOro(double valorDescuentoOro) {
        this.valorDescuentoOro = valorDescuentoOro;
    }

    public double getValorDescuentoOroTotal() {
        return valorDescuentoOroTotal;
    }

    public void setValorDescuentoOroTotal(double valorDescuentoOroTotal) {
        this.valorDescuentoOroTotal = valorDescuentoOroTotal;
    }

    public double getSubtotalSinImpuesto() {
        return subtotalSinImpuesto;
    }

    public void setSubtotalSinImpuesto(double subtotalSinImpuesto) {
        this.subtotalSinImpuesto = subtotalSinImpuesto;
    }

    public double getBaseImponible() {
        return baseImponible;
    }

    public void setBaseImponible(double baseImponible) {
        this.baseImponible = baseImponible;
    }

    public double getBaseImponibleCero() {
        return baseImponibleCero;
    }

    public void setBaseImponibleCero(double baseImponibleCero) {
        this.baseImponibleCero = baseImponibleCero;
    }

    public double getPorcentajeDescuentoManual() {
        return porcentajeDescuentoManual;
    }

    public void setPorcentajeDescuentoManual(double porcentajeDescuentoManual) {
        this.porcentajeDescuentoManual = porcentajeDescuentoManual;
    }

    public double getValorDescuentoManual() {
        return valorDescuentoManual;
    }

    public void setValorDescuentoManual(double valorDescuentoManual) {
        this.valorDescuentoManual = valorDescuentoManual;
    }

    public double getValorDescuentoManualTotal() {
        return valorDescuentoManualTotal;
    }

    public void setValorDescuentoManualTotal(double valorDescuentoManualTotal) {
        this.valorDescuentoManualTotal = valorDescuentoManualTotal;
    }

    public double getPorcentajeDescuentoAutomatico() {
        return porcentajeDescuentoAutomatico;
    }

    public void setPorcentajeDescuentoAutomatico(double porcentajeDescuentoAutomatico) {
        this.porcentajeDescuentoAutomatico = porcentajeDescuentoAutomatico;
    }

    public double getValorDescuentoAutomatico() {
        return valorDescuentoAutomatico;
    }

    public void setValorDescuentoAutomatico(double valorDescuentoAutomatico) {
        this.valorDescuentoAutomatico = valorDescuentoAutomatico;
    }

    public double getValorDescuentoAutomaticoTotal() {
        return valorDescuentoAutomaticoTotal;
    }

    public void setValorDescuentoAutomaticoTotal(double valorDescuentoAutomaticoTotal) {
        this.valorDescuentoAutomaticoTotal = valorDescuentoAutomaticoTotal;
    }

    public double getPorcentajeImpuesto() {
        return porcentajeImpuesto;
    }

    public void setPorcentajeImpuesto(double porcentajeImpuesto) {
        this.porcentajeImpuesto = porcentajeImpuesto;
    }

    public double getValorImpuesto() {
        return valorImpuesto;
    }

    public void setValorImpuesto(double valorImpuesto) {
        this.valorImpuesto = valorImpuesto;
    }

    public double getValorImpuestoTotal() {
        return valorImpuestoTotal;
    }

    public void setValorImpuestoTotal(double valorImpuestoTotal) {
        this.valorImpuestoTotal = valorImpuestoTotal;
    }

    public Producto getProducto() {
        return producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    public String getCodigoExterno() {
        return codigoExterno;
    }

    public void setCodigoExterno(String codigoExterno) {
        this.codigoExterno = codigoExterno;
    }

    public int getCantidadDevolucion() {
        return cantidadDevolucion;
    }

    public void setCantidadDevolucion(int cantidadDevolucion) {
        this.cantidadDevolucion = cantidadDevolucion;
    }

    public double getBaseICE() {
        return baseICE;
    }

    public void setBaseICE(double baseICE) {
        this.baseICE = baseICE;
    }

    @Override
    public void setValues() {
        setValue(Contract.PedidoDetalle.COLUMN_ID_PEDIDO, this.idPedido);
        setValue(Contract.PedidoDetalle.COLUMN_ID_PEDIDO_DETALLE, this.idPedidoDetalle);
        setValue(Contract.PedidoDetalle.COLUMN_ID_PEDIDO_INT, this._idPedido);
        setValue(Contract.PedidoDetalle.COLUMN_ID_PRODUCTO, this.idProducto);
        setValue(Contract.PedidoDetalle.COLUMN_DESCRIPCION, this.descripcion);
        setValue(Contract.PedidoDetalle.COLUMN_VALOR_UNITARIO, this.valorUnitario);
        setValue(Contract.PedidoDetalle.COLUMN_CANTIDAD, this.cantidad);
        setValue(Contract.PedidoDetalle.COLUMN_VALOR_TOTAL, this.valorTotal);
        setValue(Contract.PedidoDetalle.COLUMN_URL_FOTO, this.urlFoto);
        setValue(Contract.PedidoDetalle.COLUMN_SUBTOTAL, this.subtotal);
        setValue(Contract.PedidoDetalle.COLUMN_SUBTOTAL_SIN_DESCUENTO, this.subtotalSinDescuento);
        setValue(Contract.PedidoDetalle.COLUMN_SUBTOTAL_SIN_IMPUESTO, this.subtotalSinImpuesto);
        setValue(Contract.PedidoDetalle.COLUMN_BASE_IMPONIBLE, this.baseImponible);
        setValue(Contract.PedidoDetalle.COLUMN_BASE_IMPONIBLE_CERO, this.baseImponibleCero);
        setValue(Contract.PedidoDetalle.COLUMN_PORCENTAJE_DESCUENTO_MANUAL, this.porcentajeDescuentoManual);
        setValue(Contract.PedidoDetalle.COLUMN_VALOR_DESCUENTO_MANUAL, this.valorDescuentoManual);
        setValue(Contract.PedidoDetalle.COLUMN_VALOR_DESCUENTO_MANUAL_TOTAL, this.valorDescuentoManualTotal);
        setValue(Contract.PedidoDetalle.COLUMN_VALOR_DESC_AUTOMATICO, this.valorDescuentoAutomatico);
        setValue(Contract.PedidoDetalle.COLUMN_VALOR_DESC_AUTOMATICO_TOTAL, this.valorDescuentoAutomaticoTotal);
        setValue(Contract.PedidoDetalle.COLUMN_PORCENTAJE_DESCUENTO_AUTOMATICO, this.porcentajeDescuentoAutomatico);
        setValue(Contract.PedidoDetalle.COLUMN_PORCENTAJE_IMPUESTO, this.porcentajeImpuesto);
        setValue(Contract.PedidoDetalle.COLUMN_VALOR_IMPUESTO, this.valorImpuesto);
        setValue(Contract.PedidoDetalle.COLUMN_VALOR_IMPUESTO_TOTAL, this.valorImpuestoTotal);
        setValue(Contract.PedidoDetalle.COLUMN_CANTIDAD_DEVOLUCION, this.cantidadDevolucion);
        setValue(Contract.PedidoDetalle.COLUMN_BASE_ICE, this.baseICE);
        setValue(Contract.PedidoDetalle.COLUMN_PORCENTAJE_DESCUENTO_ORO, this.porcentajeDescuentoOro);
        setValue(Contract.PedidoDetalle.COLUMN_VALOR_DESCUENTO_ORO, this.valorDescuentoOro);
        setValue(Contract.PedidoDetalle.COLUMN_VALOR_DESCUENTO_ORO_TOTAL, this.valorDescuentoOroTotal);
    }

    @Override
    public Object getValue(String key) {
        return null;
    }

    @Override
    public String getDescription() {
        return null;
    }

    public static List<PedidoDetalle> getPedidoDetalles(DataBase db, int idPedido) {
        Cursor c = db.query(Contract.PedidoDetalle.TABLE_NAME, new String[] {Contract.PedidoDetalle._ID, Contract.PedidoDetalle.COLUMN_ID_PEDIDO, Contract.PedidoDetalle.COLUMN_ID_PEDIDO_DETALLE,
                Contract.PedidoDetalle.COLUMN_ID_PEDIDO_INT, Contract.PedidoDetalle.COLUMN_ID_PRODUCTO, Contract.PedidoDetalle.COLUMN_VALOR_UNITARIO, Contract.PedidoDetalle.COLUMN_CANTIDAD,
                Contract.PedidoDetalle.COLUMN_VALOR_TOTAL, Contract.PedidoDetalle.COLUMN_DESCRIPCION, Contract.PedidoDetalle.COLUMN_URL_FOTO, Contract.PedidoDetalle.COLUMN_BASE_IMPONIBLE, Contract.PedidoDetalle.COLUMN_BASE_IMPONIBLE_CERO,
                Contract.PedidoDetalle.COLUMN_SUBTOTAL, Contract.PedidoDetalle.COLUMN_SUBTOTAL_SIN_DESCUENTO, Contract.PedidoDetalle.COLUMN_SUBTOTAL_SIN_IMPUESTO, Contract.PedidoDetalle.COLUMN_PORCENTAJE_DESCUENTO_AUTOMATICO, Contract.PedidoDetalle.COLUMN_VALOR_DESC_AUTOMATICO,
                Contract.PedidoDetalle.COLUMN_VALOR_DESC_AUTOMATICO_TOTAL, Contract.PedidoDetalle.COLUMN_PORCENTAJE_DESCUENTO_MANUAL, Contract.PedidoDetalle.COLUMN_VALOR_DESCUENTO_MANUAL, Contract.PedidoDetalle.COLUMN_VALOR_DESCUENTO_MANUAL_TOTAL, Contract.PedidoDetalle.COLUMN_PORCENTAJE_IMPUESTO,
                Contract.PedidoDetalle.COLUMN_VALOR_IMPUESTO, Contract.PedidoDetalle.COLUMN_VALOR_IMPUESTO_TOTAL, Contract.PedidoDetalle.COLUMN_BASE_ICE, Contract.PedidoDetalle.COLUMN_CANTIDAD_DEVOLUCION,
                Contract.PedidoDetalle.COLUMN_PORCENTAJE_DESCUENTO_ORO, Contract.PedidoDetalle.COLUMN_VALOR_DESCUENTO_ORO, Contract.PedidoDetalle.COLUMN_VALOR_DESCUENTO_ORO_TOTAL}
                ,Contract.PedidoDetalle.COLUMN_ID_PEDIDO + " = ? ", new String[]{idPedido + ""});

        List<PedidoDetalle> list = new ArrayList<PedidoDetalle>();
        while(c.moveToNext()){
            PedidoDetalle detalle = new PedidoDetalle();
            detalle.setID(CursorUtils.getInt(c, Contract.PedidoDetalle._ID));
            detalle.set_idPedido(CursorUtils.getInt(c, Contract.PedidoDetalle.COLUMN_ID_PEDIDO_INT));
            detalle.setIdProducto(CursorUtils.getInt(c, Contract.PedidoDetalle.COLUMN_ID_PRODUCTO));
            detalle.setIdPedido(CursorUtils.getInt(c, Contract.PedidoDetalle.COLUMN_ID_PEDIDO));
            detalle.setIdPedidoDetalle(CursorUtils.getInt(c, Contract.PedidoDetalle.COLUMN_ID_PEDIDO_DETALLE));
            detalle.setValorUnitario(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_VALOR_UNITARIO));
            detalle.setCantidad(CursorUtils.getInt(c, Contract.PedidoDetalle.COLUMN_CANTIDAD));
            detalle.setValorTotal(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_VALOR_TOTAL));
            detalle.setDescripcion(CursorUtils.getString(c, Contract.PedidoDetalle.COLUMN_DESCRIPCION));
            detalle.setUrlFoto(CursorUtils.getString(c, Contract.PedidoDetalle.COLUMN_URL_FOTO));
            detalle.setPorcentajeDescuentoManual(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_PORCENTAJE_DESCUENTO_MANUAL));
            detalle.setValorDescuentoManual(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_VALOR_DESCUENTO_MANUAL));
            detalle.setValorDescuentoManualTotal(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_VALOR_DESCUENTO_MANUAL_TOTAL));
            detalle.setPorcentajeDescuentoAutomatico(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_PORCENTAJE_DESCUENTO_AUTOMATICO));
            detalle.setValorDescuentoAutomatico(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_VALOR_DESC_AUTOMATICO));
            detalle.setValorDescuentoAutomaticoTotal(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_VALOR_DESC_AUTOMATICO_TOTAL));
            detalle.setPorcentajeImpuesto(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_PORCENTAJE_IMPUESTO));
            detalle.setValorImpuesto(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_VALOR_IMPUESTO));
            detalle.setValorImpuestoTotal(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_VALOR_IMPUESTO_TOTAL));
            detalle.setSubtotal(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_SUBTOTAL));
            detalle.setSubtotalSinDescuento(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_SUBTOTAL_SIN_DESCUENTO));
            detalle.setSubtotalSinImpuesto(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_SUBTOTAL_SIN_IMPUESTO));
            detalle.setBaseImponible(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_BASE_IMPONIBLE));
            detalle.setBaseImponibleCero(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_BASE_IMPONIBLE_CERO));
            detalle.setBaseICE(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_BASE_ICE));
            detalle.setCantidadDevolucion(CursorUtils.getInt(c, Contract.PedidoDetalle.COLUMN_CANTIDAD_DEVOLUCION));
            detalle.setPorcentajeDescuentoOro(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_PORCENTAJE_DESCUENTO_ORO));
            detalle.setValorDescuentoOro(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_VALOR_DESCUENTO_ORO));
            detalle.setValorDescuentoOroTotal(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_VALOR_DESCUENTO_ORO_TOTAL));
            detalle.setCodigoExterno(Producto.getProductoIdServer(db, detalle.getIdProducto()).getCodigoExterno());
            detalle.setProducto(Producto.getProductoIdServer(db, detalle.getIdProducto()));
            list.add(detalle);
        }
        c.close();
        return list;
    }

    public static List<PedidoDetalle> getPedidoDetallesInt(DataBase db, long idPedido) {
        Cursor c = db.query(Contract.PedidoDetalle.TABLE_NAME, new String[] {Contract.PedidoDetalle._ID, Contract.PedidoDetalle.COLUMN_ID_PEDIDO, Contract.PedidoDetalle.COLUMN_ID_PEDIDO_DETALLE,
                Contract.PedidoDetalle.COLUMN_ID_PEDIDO_INT, Contract.PedidoDetalle.COLUMN_ID_PRODUCTO, Contract.PedidoDetalle.COLUMN_VALOR_UNITARIO, Contract.PedidoDetalle.COLUMN_CANTIDAD,
                Contract.PedidoDetalle.COLUMN_VALOR_TOTAL, Contract.PedidoDetalle.COLUMN_DESCRIPCION, Contract.PedidoDetalle.COLUMN_URL_FOTO, Contract.PedidoDetalle.COLUMN_BASE_IMPONIBLE, Contract.PedidoDetalle.COLUMN_BASE_IMPONIBLE_CERO,
                Contract.PedidoDetalle.COLUMN_SUBTOTAL, Contract.PedidoDetalle.COLUMN_SUBTOTAL_SIN_DESCUENTO, Contract.PedidoDetalle.COLUMN_SUBTOTAL_SIN_IMPUESTO, Contract.PedidoDetalle.COLUMN_PORCENTAJE_DESCUENTO_AUTOMATICO, Contract.PedidoDetalle.COLUMN_VALOR_DESC_AUTOMATICO,
                Contract.PedidoDetalle.COLUMN_VALOR_DESC_AUTOMATICO_TOTAL, Contract.PedidoDetalle.COLUMN_PORCENTAJE_DESCUENTO_MANUAL, Contract.PedidoDetalle.COLUMN_VALOR_DESCUENTO_MANUAL, Contract.PedidoDetalle.COLUMN_VALOR_DESCUENTO_MANUAL_TOTAL, Contract.PedidoDetalle.COLUMN_PORCENTAJE_IMPUESTO,
                Contract.PedidoDetalle.COLUMN_VALOR_IMPUESTO, Contract.PedidoDetalle.COLUMN_VALOR_IMPUESTO_TOTAL,  Contract.PedidoDetalle.COLUMN_BASE_ICE, Contract.PedidoDetalle.COLUMN_CANTIDAD_DEVOLUCION,
                Contract.PedidoDetalle.COLUMN_PORCENTAJE_DESCUENTO_ORO, Contract.PedidoDetalle.COLUMN_VALOR_DESCUENTO_ORO, Contract.PedidoDetalle.COLUMN_VALOR_DESCUENTO_ORO_TOTAL}
                ,Contract.PedidoDetalle.COLUMN_ID_PEDIDO_INT + " = ? ", new String[]{idPedido + ""});

        List<PedidoDetalle> list = new ArrayList<PedidoDetalle>();
        while(c.moveToNext()){
            PedidoDetalle detalle = new PedidoDetalle();
            detalle.setID(CursorUtils.getInt(c, Contract.PedidoDetalle._ID));
            detalle.set_idPedido(CursorUtils.getInt(c, Contract.PedidoDetalle.COLUMN_ID_PEDIDO_INT));
            detalle.setIdProducto(CursorUtils.getInt(c, Contract.PedidoDetalle.COLUMN_ID_PRODUCTO));
            detalle.setIdPedido(CursorUtils.getInt(c, Contract.PedidoDetalle.COLUMN_ID_PEDIDO));
            detalle.setIdPedidoDetalle(CursorUtils.getInt(c, Contract.PedidoDetalle.COLUMN_ID_PEDIDO_DETALLE));
            detalle.setValorUnitario(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_VALOR_UNITARIO));
            detalle.setCantidad(CursorUtils.getInt(c, Contract.PedidoDetalle.COLUMN_CANTIDAD));
            detalle.setValorTotal(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_VALOR_TOTAL));
            detalle.setDescripcion(CursorUtils.getString(c, Contract.PedidoDetalle.COLUMN_DESCRIPCION));
            detalle.setUrlFoto(CursorUtils.getString(c, Contract.PedidoDetalle.COLUMN_URL_FOTO));
            detalle.setPorcentajeDescuentoManual(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_PORCENTAJE_DESCUENTO_MANUAL));
            detalle.setValorDescuentoManual(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_VALOR_DESCUENTO_MANUAL));
            detalle.setValorDescuentoManualTotal(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_VALOR_DESCUENTO_MANUAL_TOTAL));
            detalle.setPorcentajeDescuentoAutomatico(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_PORCENTAJE_DESCUENTO_AUTOMATICO));
            detalle.setValorDescuentoAutomatico(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_VALOR_DESC_AUTOMATICO));
            detalle.setValorDescuentoAutomaticoTotal(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_VALOR_DESC_AUTOMATICO_TOTAL));
            detalle.setPorcentajeImpuesto(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_PORCENTAJE_IMPUESTO));
            detalle.setValorImpuesto(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_VALOR_IMPUESTO));
            detalle.setValorImpuestoTotal(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_VALOR_IMPUESTO_TOTAL));
            detalle.setSubtotal(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_SUBTOTAL));
            detalle.setSubtotalSinDescuento(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_SUBTOTAL_SIN_DESCUENTO));
            detalle.setSubtotalSinImpuesto(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_SUBTOTAL_SIN_IMPUESTO));
            detalle.setBaseImponible(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_BASE_IMPONIBLE));
            detalle.setBaseImponibleCero(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_BASE_IMPONIBLE_CERO));
            detalle.setBaseICE(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_BASE_ICE));
            detalle.setCantidadDevolucion(CursorUtils.getInt(c, Contract.PedidoDetalle.COLUMN_CANTIDAD_DEVOLUCION));
            detalle.setPorcentajeDescuentoOro(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_PORCENTAJE_DESCUENTO_ORO));
            detalle.setValorDescuentoOro(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_VALOR_DESCUENTO_ORO));
            detalle.setValorDescuentoOroTotal(CursorUtils.getDouble(c, Contract.PedidoDetalle.COLUMN_VALOR_DESCUENTO_ORO_TOTAL));
            detalle.setCodigoExterno(Producto.getProductoIdServer(db, detalle.getIdProducto()).getCodigoExterno());
            detalle.setProducto(Producto.getProductoIdServer(db, detalle.getIdProducto()));

            list.add(detalle);
        }
        c.close();
        return list;
    }

    public static void deleteDetallesByIdPedido(DataBase db, int idPedido)
    {
        db.delete(Contract.PedidoDetalle.TABLE_NAME, Contract.PedidoDetalle.COLUMN_ID_PEDIDO + " = ?", new String[]{idPedido + ""});
    }

    public static void deleteDetallesByIdPedidoInt(DataBase db, int idPedido)
    {
        db.delete(Contract.PedidoDetalle.TABLE_NAME, Contract.PedidoDetalle.COLUMN_ID_PEDIDO_INT + " = ?", new String[]{idPedido + ""});
    }
}