package rp3.marketforce.models.pedido;

import android.database.Cursor;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;
import rp3.marketforce.db.Contract;
import rp3.util.CursorUtils;

/**
 * Created by magno_000 on 06/04/2017.
 */

public class SecuenciaMatriz extends EntityBase<SecuenciaMatriz> {

    private long id;
    private int idJerarquia;
    private String matriz;
    private Date fechaEfectiva;
    private Date fechaVencimiento;

    @Override
    public long getID() {
        return id;
    }

    @Override
    public void setID(long id) {
        this.id = id;
    }

    @Override
    public boolean isAutoGeneratedId() {
        return true;
    }

    @Override
    public String getTableName() {
        return Contract.SecuenciaMatriz.TABLE_NAME;
    }

    public int getIdJerarquia() {
        return idJerarquia;
    }

    public void setIdJerarquia(int idJerarquia) {
        this.idJerarquia = idJerarquia;
    }

    public String getMatriz() {
        return matriz;
    }

    public void setMatriz(String matriz) {
        this.matriz = matriz;
    }

    public Date getFechaEfectiva() {
        return fechaEfectiva;
    }

    public void setFechaEfectiva(Date fechaEfectiva) {
        this.fechaEfectiva = fechaEfectiva;
    }

    public Date getFechaVencimiento() {
        return fechaVencimiento;
    }

    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }

    @Override
    public void setValues() {
        setValue(Contract.SecuenciaMatriz.COLUMN_ID_JERARQUIA, this.idJerarquia);
        setValue(Contract.SecuenciaMatriz.COLUMN_MATRIZ, this.matriz);
        setValue(Contract.SecuenciaMatriz.COLUMN_FECHA_EFECTIVA, this.fechaEfectiva);
        setValue(Contract.SecuenciaMatriz.COLUMN_FECHA_VENCIMIENTO, this.fechaVencimiento);
    }

    @Override
    public Object getValue(String key) {
        return id;
    }

    @Override
    public String getDescription() {
        return matriz;
    }

    /*public static List<Banco> getBancos(DataBase db) {
        Cursor c = db.query(Contract.Banco.TABLE_NAME, new String[] {Contract.Banco._ID, Contract.Banco.COLUMN_ID_BANCO, Contract.Banco.COLUMN_DESCRIPCION});

        List<Banco> list = new ArrayList<Banco>();
        while(c.moveToNext()){
            Banco banco = new Banco();
            banco.setID(CursorUtils.getInt(c, Contract.Banco._ID));
            banco.setIdBanco(CursorUtils.getInt(c, Contract.Banco.COLUMN_ID_BANCO));
            banco.setDescripcion(CursorUtils.getString(c, Contract.Banco.COLUMN_DESCRIPCION));
            list.add(banco);
        }
        c.close();
        return list;
    }*/
}
