package rp3.marketforce.models.pedido;

import android.database.Cursor;

import java.util.ArrayList;
import java.util.List;

import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;
import rp3.marketforce.db.Contract;
import rp3.util.CursorUtils;

/**
 * Created by magno_000 on 04/11/2015.
 */
public class SubCategoria extends EntityBase<SubCategoria> {

    private long id;
    private int idSubCategoria;
    private int idCategoria;
    private String descripcion;

    @Override
    public long getID() {
        return id;
    }

    @Override
    public void setID(long id) {
        this.id = id;
    }

    @Override
    public boolean isAutoGeneratedId() {
        return true;
    }

    @Override
    public String getTableName() {
        return Contract.SubCategoria.TABLE_NAME;
    }

    public int getIdCategoria() {
        return idCategoria;
    }

    public void setIdCategoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public int getIdSubCategoria() {
        return idSubCategoria;
    }

    public void setIdSubCategoria(int idSubCategoria) {
        this.idSubCategoria = idSubCategoria;
    }

    @Override
    public void setValues() {
        setValue(Contract.SubCategoria.COLUMN_ID_SUBCATEGORIA, this.idSubCategoria);
        setValue(Contract.SubCategoria.COLUMN_ID_CATEGORIA, this.idCategoria);
        setValue(Contract.SubCategoria.COLUMN_DESCRIPCION, this.descripcion);
    }

    @Override
    public Object getValue(String key) {
        return null;
    }

    @Override
    public String getDescription() {
        return null;
    }

    public static List<SubCategoria> getSubCategorias(DataBase db) {
        Cursor c = db.query(Contract.SubCategoria.TABLE_NAME, new String[] {Contract.SubCategoria._ID, Contract.SubCategoria.COLUMN_ID_CATEGORIA, Contract.SubCategoria.COLUMN_DESCRIPCION, Contract.SubCategoria.COLUMN_ID_SUBCATEGORIA,});

        List<SubCategoria> list = new ArrayList<SubCategoria>();
        while(c.moveToNext()){
            SubCategoria categoria = new SubCategoria();
            categoria.setID(CursorUtils.getInt(c, Contract.SubCategoria._ID));
            categoria.setIdCategoria(CursorUtils.getInt(c, Contract.SubCategoria.COLUMN_ID_CATEGORIA));
            categoria.setIdSubCategoria(CursorUtils.getInt(c, Contract.SubCategoria.COLUMN_ID_SUBCATEGORIA));
            categoria.setDescripcion(CursorUtils.getString(c, Contract.SubCategoria.COLUMN_DESCRIPCION));
            list.add(categoria);
        }
        c.close();
        return list;
    }

    public static List<SubCategoria> getSubCategorias(DataBase db, int idCategoria) {
        Cursor c = db.query(Contract.SubCategoria.TABLE_NAME, new String[] {Contract.SubCategoria._ID, Contract.SubCategoria.COLUMN_ID_CATEGORIA, Contract.SubCategoria.COLUMN_DESCRIPCION, Contract.SubCategoria.COLUMN_ID_SUBCATEGORIA,},
                Contract.SubCategoria.COLUMN_ID_CATEGORIA + " = ?", new String[]{idCategoria + ""} );

        List<SubCategoria> list = new ArrayList<SubCategoria>();
        while(c.moveToNext()){
            SubCategoria categoria = new SubCategoria();
            categoria.setID(CursorUtils.getInt(c, Contract.SubCategoria._ID));
            categoria.setIdCategoria(CursorUtils.getInt(c, Contract.SubCategoria.COLUMN_ID_CATEGORIA));
            categoria.setIdSubCategoria(CursorUtils.getInt(c, Contract.SubCategoria.COLUMN_ID_SUBCATEGORIA));
            categoria.setDescripcion(CursorUtils.getString(c, Contract.SubCategoria.COLUMN_DESCRIPCION));
            list.add(categoria);
        }
        c.close();
        return list;
    }

    public static SubCategoria getSubCategoria(DataBase db, int idSubCategoria) {
        Cursor c = db.query(Contract.SubCategoria.TABLE_NAME, new String[] {Contract.SubCategoria._ID, Contract.SubCategoria.COLUMN_ID_CATEGORIA, Contract.SubCategoria.COLUMN_DESCRIPCION, Contract.SubCategoria.COLUMN_ID_SUBCATEGORIA,},
                Contract.SubCategoria.COLUMN_ID_SUBCATEGORIA + " = ?", new String[]{idSubCategoria + ""} );

        SubCategoria categoria = new SubCategoria();
        while(c.moveToNext()){

            categoria.setID(CursorUtils.getInt(c, Contract.SubCategoria._ID));
            categoria.setIdCategoria(CursorUtils.getInt(c, Contract.SubCategoria.COLUMN_ID_CATEGORIA));
            categoria.setIdSubCategoria(CursorUtils.getInt(c, Contract.SubCategoria.COLUMN_ID_SUBCATEGORIA));
            categoria.setDescripcion(CursorUtils.getString(c, Contract.SubCategoria.COLUMN_DESCRIPCION));

        }
        c.close();
        return categoria;
    }

}