package rp3.marketforce.models.marcacion;

import android.database.Cursor;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;
import rp3.marketforce.db.Contract;
import rp3.util.CursorUtils;

/**
 * Created by magno_000 on 08/06/2015.
 */
public class Permiso extends EntityBase<Marcacion>
{
    private long id;
    private long idMarcacion;
    private Date fecha;
    private String tipo;
    private String observacion;

    @Override
    public long getID() {
        // TODO Auto-generated method stub
        return id;
    }

    @Override
    public void setID(long id) {
        this.id = id;

    }

    public long getIdMarcacion() {
        return idMarcacion;
    }

    public void setIdMarcacion(long idMarcacion) {
        this.idMarcacion = idMarcacion;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public String getObservacion() {
        return observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    @Override
    public boolean isAutoGeneratedId() {
        // TODO Auto-generated method stub
        return true;
    }

    @Override
    public String getTableName() {
        // TODO Auto-generated method stub
        return Contract.Permiso.TABLE_NAME;
    }

    @Override
    public void setValues() {
        setValue(Contract.Permiso.COLUMN_OBSERVACION, this.observacion);
        setValue(Contract.Permiso.COLUMN_FECHA, this.fecha);
        setValue(Contract.Permiso.COLUMN_ID_MARCACION, this.idMarcacion);
        setValue(Contract.Permiso.COLUMN_TIPO, this.tipo);
    }

    @Override
    public Object getValue(String key) {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    public String getDescription() {
        // TODO Auto-generated method stub
        return null;
    }

    public static Permiso getPermisoMarcacion(DataBase db, long idMarcacion) {
        Cursor c = db.query(Contract.Permiso.TABLE_NAME, new String[]{Contract.Permiso._ID, Contract.Permiso.COLUMN_FECHA,
                        Contract.Permiso.COLUMN_TIPO, Contract.Permiso.COLUMN_OBSERVACION, Contract.Permiso.COLUMN_ID_MARCACION}, Contract.Permiso.COLUMN_ID_MARCACION + " = ? ",
                new String[]{idMarcacion + ""});
        Permiso permiso = new Permiso();

        if (c.moveToFirst()) {

            permiso.setID(CursorUtils.getLong(c, Contract.Permiso._ID));
            permiso.setIdMarcacion(CursorUtils.getLong(c, Contract.Permiso.COLUMN_ID_MARCACION));
            permiso.setTipo(CursorUtils.getString(c, Contract.Permiso.COLUMN_TIPO));
            permiso.setFecha(CursorUtils.getDate(c, Contract.Permiso.COLUMN_FECHA));
            permiso.setObservacion(CursorUtils.getString(c, Contract.Permiso.COLUMN_OBSERVACION));
        }

        return permiso;

    }
}
