package rp3.auna.models.ventanueva;

import android.database.Cursor;
import android.util.Log;

import java.util.ArrayList;
import java.util.List;

import rp3.auna.db.Contract;
import rp3.db.QueryDir;
import rp3.db.sqlite.DataBase;
import rp3.util.CursorUtils;

/**
 * Created by Jesus Villa on 02/01/2018.
 */

public class ComisionesVta extends rp3.data.entity.EntityBase<ComisionesVta>  {
    private static final String TAG = ComisionesVta.class.getSimpleName();
    private long id;
    private int idAgente;
    private int pkAsesor;
    private String nombreAsesor;
    private String ventas;
    private String incentivo;
    private String comision;

    //region Encapsulamiento

    public int getIdAgente() {
        return idAgente;
    }

    public void setIdAgente(int idAgente) {
        this.idAgente = idAgente;
    }

    public int getPkAsesor() {
        return pkAsesor;
    }

    public void setPkAsesor(int pkAsesor) {
        this.pkAsesor = pkAsesor;
    }

    public String getNombreAsesor() {
        return nombreAsesor;
    }

    public void setNombreAsesor(String nombreAsesor) {
        this.nombreAsesor = nombreAsesor;
    }

    public String getVentas() {
        return ventas;
    }

    public void setVentas(String ventas) {
        this.ventas = ventas;
    }

    public String getIncentivo() {
        return incentivo;
    }

    public void setIncentivo(String incentivo) {
        this.incentivo = incentivo;
    }

    public String getComision() {
        return comision;
    }

    public void setComision(String comision) {
        this.comision = comision;
    }


    //endregion

    //region Database

    @Override
    public long getID() {
        return id;
    }

    @Override
    public void setID(long id) {
        this.id = id;
    }

    @Override
    public boolean isAutoGeneratedId() {
        return true;
    }

    @Override
    public String getTableName() {
        return "tbAgenteComisiones";
    }

    @Override
    public void setValues() {
        setValue(Contract.ComisionAgente.COLUMN_COMISION_AGENTE_ID, this.idAgente);
        setValue(Contract.ComisionAgente.COLUMN_COMISION_PK_ASESOR, this.pkAsesor);
        setValue(Contract.ComisionAgente.COLUMN_COMISION_NOMBRE_ASESOR, this.nombreAsesor);
        setValue(Contract.ComisionAgente.COLUMN_COMISION_VENTAS,this.ventas);
        setValue(Contract.ComisionAgente.COLUMN_COMISION_INCENTIVO,this.incentivo);
        setValue(Contract.ComisionAgente.COLUMN_COMISION_COMISION,this.comision);
    }

    @Override
    public Object getValue(String key) {
        return null;
    }

    @Override
    public String getDescription() {
        return null;
    }

    //endregion

    //region Querys

    public static ComisionesVta getAll(DataBase db) {
        String query = (Contract.ComisionAgente.QUERY_ALL);

        Cursor c = db.rawQuery(query);
        List<ComisionesVta> list = new ArrayList<ComisionesVta>();

        if(c.moveToFirst()){
            do
            {
                ComisionesVta comisionesVta =  new ComisionesVta();
                comisionesVta.setID(CursorUtils.getInt(c,Contract.ComisionAgente._ID));
                comisionesVta.setIdAgente(CursorUtils.getInt(c,Contract.ComisionAgente.COLUMN_COMISION_AGENTE_ID));
                comisionesVta.setPkAsesor(CursorUtils.getInt(c, Contract.ComisionAgente.COLUMN_COMISION_PK_ASESOR));
                comisionesVta.setNombreAsesor(CursorUtils.getString(c, Contract.ComisionAgente.COLUMN_COMISION_NOMBRE_ASESOR));
                comisionesVta.setVentas(CursorUtils.getString(c, Contract.ComisionAgente.COLUMN_COMISION_VENTAS));
                comisionesVta.setIncentivo(CursorUtils.getString(c,Contract.ComisionAgente.COLUMN_COMISION_INCENTIVO));
                comisionesVta.setComision(CursorUtils.getString(c,Contract.ComisionAgente.COLUMN_COMISION_COMISION));
                Log.d(TAG,comisionesVta.toString());
                list.add(comisionesVta);
            }while(c.moveToNext());
        }
        c.close();
        if(list.size()>0){
            return list.get(0);
        }
        return null;
    }

    //endregion

    @Override
    public String toString() {
        return "ComisionesVta{" +
                "id=" + id +
                ", idAgente=" + idAgente +
                ", pkAsesor=" + pkAsesor +
                ", nombreAsesor='" + nombreAsesor + '\'' +
                ", ventas='" + ventas + '\'' +
                ", incentivo='" + incentivo + '\'' +
                ", comision='" + comision + '\'' +
                '}';
    }
}
