package rp3.auna.models.pedido;

import android.database.Cursor;

import java.util.ArrayList;
import java.util.List;

import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;
import rp3.auna.db.Contract;
import rp3.util.CursorUtils;

/**
 * Created by magno_000 on 22/04/2016.
 */
public class Banco extends EntityBase<Banco> {

    private long id;
    private int idBanco;
    private String descripcion;

    @Override
    public long getID() {
        return id;
    }

    @Override
    public void setID(long id) {
        this.id = id;
    }

    @Override
    public boolean isAutoGeneratedId() {
        return true;
    }

    @Override
    public String getTableName() {
        return Contract.Banco.TABLE_NAME;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public int getIdBanco() {
        return idBanco;
    }

    public void setIdBanco(int idBanco) {
        this.idBanco = idBanco;
    }

    @Override
    public void setValues() {
        setValue(Contract.Banco.COLUMN_ID_BANCO, this.idBanco);
        setValue(Contract.Banco.COLUMN_DESCRIPCION, this.descripcion);
    }

    @Override
    public Object getValue(String key) {
        return idBanco;
    }

    @Override
    public String getDescription() {
        return descripcion;
    }

    public static List<Banco> getBancos(DataBase db) {
        Cursor c = db.query(Contract.Banco.TABLE_NAME, new String[] {Contract.Banco._ID, Contract.Banco.COLUMN_ID_BANCO, Contract.Banco.COLUMN_DESCRIPCION});

        List<Banco> list = new ArrayList<Banco>();
        while(c.moveToNext()){
            Banco banco = new Banco();
            banco.setID(CursorUtils.getInt(c, Contract.Banco._ID));
            banco.setIdBanco(CursorUtils.getInt(c, Contract.Banco.COLUMN_ID_BANCO));
            banco.setDescripcion(CursorUtils.getString(c, Contract.Banco.COLUMN_DESCRIPCION));
            list.add(banco);
        }
        c.close();
        return list;
    }
}