package rp3.auna.models.auna;

import android.database.Cursor;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import rp3.auna.db.Contract;
import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;
import rp3.util.CursorUtils;

/**
 * Created by magno_000 on 30/01/2017.
 */
public class AgendaLlamada extends EntityBase<AgendaLlamada> {

    private long id;
    private int idAgenda;
    private long _idAgenda;
    private int idAgendaLlamada;
    private Date fecha;
    private int duracion;
    private String numero;

    @Override
    public long getID() {
        return id;
    }

    @Override
    public void setID(long id) {
        this.id = id;
    }

    public int getIdAgenda() {
        return idAgenda;
    }

    public void setIdAgenda(int idAgenda) {
        this.idAgenda = idAgenda;
    }

    public long get_idAgenda() {
        return _idAgenda;
    }

    public void set_idAgenda(long _idAgenda) {
        this._idAgenda = _idAgenda;
    }

    public int getIdAgendaLlamada() {
        return idAgendaLlamada;
    }

    public void setIdAgendaLlamada(int idAgendaLlamada) {
        this.idAgendaLlamada = idAgendaLlamada;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public int getDuracion() {
        return duracion;
    }

    public void setDuracion(int duracion) {
        this.duracion = duracion;
    }

    public String getNumero() {
        return numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    @Override
    public boolean isAutoGeneratedId() {
        return true;
    }

    @Override
    public String getTableName() {
        return Contract.AgendaLlamada.TABLE_NAME;
    }

    @Override
    public void setValues() {
        setValue(Contract.AgendaLlamada.COLUMN_AGENDA_ID, this.idAgenda);
        setValue(Contract.AgendaLlamada.COLUMN_AGENDA_ID_EXT, this._idAgenda);
        setValue(Contract.AgendaLlamada.COLUMN_AGENDA_LLAMADA_ID, this.idAgendaLlamada);
        setValue(Contract.AgendaLlamada.COLUMN_NUMERO, this.numero);
        setValue(Contract.AgendaLlamada.COLUMN_FECHA, this.fecha);
        setValue(Contract.AgendaLlamada.COLUMN_DURACION, this.duracion);
    }

    @Override
    public Object getValue(String key) {
        return null;
    }

    @Override
    public String getDescription() {
        return null;
    }

    public static List<AgendaLlamada> getLlamadasByIdAgenda(DataBase db, long idAgenda) {
        Cursor c = db.query(Contract.AgendaLlamada.TABLE_NAME, new String[] {Contract.AgendaLlamada._ID, Contract.AgendaLlamada.COLUMN_AGENDA_ID,
                Contract.AgendaLlamada.COLUMN_AGENDA_ID_EXT, Contract.AgendaLlamada.COLUMN_AGENDA_LLAMADA_ID, Contract.AgendaLlamada.COLUMN_FECHA, Contract.AgendaLlamada.COLUMN_NUMERO,
                Contract.AgendaLlamada.COLUMN_DURACION},Contract.AgendaLlamada.COLUMN_AGENDA_ID_EXT + " = ?", new String[]{idAgenda + ""}, null,null, null);

        List<AgendaLlamada> list = new ArrayList<AgendaLlamada>();
        while(c.moveToNext()){
            AgendaLlamada llamada = new AgendaLlamada();
            llamada.setID(CursorUtils.getInt(c, Contract.AgendaLlamada._ID));
            llamada.setIdAgenda(CursorUtils.getInt(c, Contract.AgendaLlamada.COLUMN_AGENDA_ID));
            llamada.set_idAgenda(CursorUtils.getLong(c, Contract.AgendaLlamada.COLUMN_AGENDA_ID_EXT));
            llamada.setIdAgendaLlamada(CursorUtils.getInt(c, Contract.AgendaLlamada.COLUMN_AGENDA_LLAMADA_ID));
            llamada.setNumero(CursorUtils.getString(c, Contract.AgendaLlamada.COLUMN_NUMERO));
            llamada.setFecha(CursorUtils.getDate(c, Contract.AgendaLlamada.COLUMN_FECHA));
            llamada.setDuracion(CursorUtils.getInt(c, Contract.AgendaLlamada.COLUMN_DURACION));
            list.add(llamada);
        }
        c.close();
        return list;
    }
}