package rp3.auna.models.auna;

import android.database.Cursor;

import java.util.ArrayList;
import java.util.List;

import rp3.auna.db.Contract;
import rp3.auna.models.AgendaTareaActividades;
import rp3.db.QueryDir;
import rp3.db.sqlite.DataBase;
import rp3.util.CursorUtils;

/**
 * Created by magno_000 on 03/02/2017.
 */
public class Cotizacion extends rp3.data.entity.EntityBase<Cotizacion> {

    private long id;
    private int idRuta;
    private long idAgenda;
    private long _idAgenda;
    private int idTarea;
    private String parametros;
    private String response;
    private int opcion;
    private double valor;

    @Override
    public long getID() {
        return id;
    }

    @Override
    public void setID(long id) {
        this.id = id;
    }

    @Override
    public boolean isAutoGeneratedId() {
        return true;
    }

    @Override
    public String getTableName() {
        return Contract.Cotizacion.TABLE_NAME;
    }

    public int getIdTarea() {
        return idTarea;
    }

    public void setIdTarea(int idTarea) {
        this.idTarea = idTarea;
    }

    public String getParametros() {
        return parametros;
    }

    public void setParametros(String parametros) {
        this.parametros = parametros;
    }

    public String getResponse() {
        return response;
    }

    public void setResponse(String response) {
        this.response = response;
    }

    public int getOpcion() {
        return opcion;
    }

    public void setOpcion(int opcion) {
        this.opcion = opcion;
    }

    public double getValor() {
        return valor;
    }

    public void setValor(double valor) {
        this.valor = valor;
    }

    @Override
    public void setValues() {

        setValue(Contract.Cotizacion.COLUMN_RUTA_ID, this.idRuta);
        setValue(Contract.Cotizacion.COLUMN_AGENDA_ID, this.idAgenda);
        setValue(Contract.Cotizacion.COLUMN_AGENDA_ID_EXT, this._idAgenda);
        setValue(Contract.Cotizacion.COLUMN_TAREA_ID, this.idTarea);
        setValue(Contract.Cotizacion.COLUMN_PARAMETROS, this.parametros);
        setValue(Contract.Cotizacion.COLUMN_RESPONSE, this.response);
        setValue(Contract.Cotizacion.COLUMN_OPCION, this.opcion);
        setValue(Contract.Cotizacion.COLUMN_VALOR, this.valor);
    }

    @Override
    public Object getValue(String key) {
        return null;
    }

    @Override
    public String getDescription() {
        return null;
    }

    public int getIdRuta() {
        return idRuta;
    }

    public void setIdRuta(int idRuta) {
        this.idRuta = idRuta;
    }

    public long getIdAgenda() {
        return idAgenda;
    }

    public void setIdAgenda(long idAgenda) {
        this.idAgenda = idAgenda;
    }

    public long get_idAgenda() {
        return _idAgenda;
    }

    public void set_idAgenda(long _idAgenda) {
        this._idAgenda = _idAgenda;
    }

    public static Cotizacion getCotizacion(DataBase db, long idAgenda, int idRuta, int idTarea){

        Cursor c = db.query(Contract.Cotizacion.TABLE_NAME, new String[] {Contract.Cotizacion._ID, Contract.Cotizacion.COLUMN_AGENDA_ID,
                        Contract.Cotizacion.COLUMN_PARAMETROS, Contract.Cotizacion.COLUMN_RUTA_ID, Contract.Cotizacion.COLUMN_AGENDA_ID_EXT,
                        Contract.Cotizacion.COLUMN_TAREA_ID, Contract.Cotizacion.COLUMN_RESPONSE, Contract.Cotizacion.COLUMN_OPCION, Contract.Cotizacion.COLUMN_VALOR},
                Contract.Cotizacion.COLUMN_AGENDA_ID + " = ?  ", new String[] { idAgenda + ""});


        Cotizacion cotizacion = new Cotizacion();
        if(c.moveToFirst()){

            cotizacion.setID(CursorUtils.getInt(c, Contract.Cotizacion._ID));
            cotizacion.setIdRuta(CursorUtils.getInt(c, Contract.Cotizacion.COLUMN_RUTA_ID));
            cotizacion.setIdTarea(CursorUtils.getInt(c, Contract.Cotizacion.COLUMN_TAREA_ID));
            cotizacion.setIdAgenda(CursorUtils.getLong(c, Contract.Cotizacion.COLUMN_AGENDA_ID));
            cotizacion.set_idAgenda(CursorUtils.getInt(c, Contract.Cotizacion.COLUMN_AGENDA_ID_EXT));
            cotizacion.setParametros(CursorUtils.getString(c, Contract.Cotizacion.COLUMN_PARAMETROS));
            cotizacion.setResponse(CursorUtils.getString(c, Contract.Cotizacion.COLUMN_RESPONSE));
            cotizacion.setOpcion(CursorUtils.getInt(c, Contract.Cotizacion.COLUMN_OPCION));
            cotizacion.setValor(CursorUtils.getDouble(c, Contract.Cotizacion.COLUMN_VALOR));

        }
        c.close();
        return cotizacion;
    }

    public static Cotizacion getCotizacionInt(DataBase db, long idAgenda, int idRuta, int idTarea){

        Cursor c = db.query(Contract.Cotizacion.TABLE_NAME, new String[] {Contract.Cotizacion._ID, Contract.Cotizacion.COLUMN_AGENDA_ID,
                        Contract.Cotizacion.COLUMN_PARAMETROS, Contract.Cotizacion.COLUMN_RUTA_ID, Contract.Cotizacion.COLUMN_AGENDA_ID_EXT,
                        Contract.Cotizacion.COLUMN_TAREA_ID, Contract.Cotizacion.COLUMN_RESPONSE, Contract.Cotizacion.COLUMN_OPCION, Contract.Cotizacion.COLUMN_VALOR},
                Contract.Cotizacion.COLUMN_AGENDA_ID_EXT + " = ? ", new String[] { idAgenda + ""});


        Cotizacion cotizacion = new Cotizacion();
        if(c.moveToFirst()){

            cotizacion.setID(CursorUtils.getInt(c, Contract.Cotizacion._ID));
            cotizacion.setIdRuta(CursorUtils.getInt(c, Contract.Cotizacion.COLUMN_RUTA_ID));
            cotizacion.setIdTarea(CursorUtils.getInt(c, Contract.Cotizacion.COLUMN_TAREA_ID));
            cotizacion.setIdAgenda(CursorUtils.getLong(c, Contract.Cotizacion.COLUMN_AGENDA_ID));
            cotizacion.set_idAgenda(CursorUtils.getInt(c, Contract.Cotizacion.COLUMN_AGENDA_ID_EXT));
            cotizacion.setParametros(CursorUtils.getString(c, Contract.Cotizacion.COLUMN_PARAMETROS));
            cotizacion.setResponse(CursorUtils.getString(c, Contract.Cotizacion.COLUMN_RESPONSE));
            cotizacion.setOpcion(CursorUtils.getInt(c, Contract.Cotizacion.COLUMN_OPCION));
            cotizacion.setValor(CursorUtils.getDouble(c, Contract.Cotizacion.COLUMN_VALOR));

        }
        c.close();
        return cotizacion;
    }
}