package rp3.berlin.models.pedido;

import android.database.Cursor;

import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;
import rp3.berlin.db.Contract;
import rp3.util.CursorUtils;

/**
 * Created by magno_000 on 24/04/2017.
 */

public class AgenteDescuento extends EntityBase<AgenteDescuento> {

    private long id;
    private String canal;
    private String linea;
    private double tope;

    @Override
    public long getID() {
        return id;
    }

    @Override
    public void setID(long id) {
        this.id = id;
    }

    @Override
    public boolean isAutoGeneratedId() {
        return true;
    }

    @Override
    public String getTableName() {
        return Contract.AgenteDescuento.TABLE_NAME;
    }

    @Override
    public void setValues() {
        setValue(Contract.AgenteDescuento.COLUMN_CANAL, this.canal);
        setValue(Contract.AgenteDescuento.COLUMN_LINEA, this.linea);
        setValue(Contract.AgenteDescuento.COLUMN_TOPE, this.tope);
    }

    @Override
    public Object getValue(String key) {
        return canal;
    }

    @Override
    public String getDescription() {
        return linea;
    }

    public String getCanal() {
        return canal;
    }

    public void setCanal(String canal) {
        this.canal = canal;
    }

    public String getLinea() {
        return linea;
    }

    public void setLinea(String linea) {
        this.linea = linea;
    }

    public double getTope() {
        return tope;
    }

    public void setTope(double tope) {
        this.tope = tope;
    }

    public static AgenteDescuento getTopeDescuento(DataBase db, String canal, String linea) {
        Cursor c = db.query(Contract.AgenteDescuento.TABLE_NAME, new String[] {Contract.AgenteDescuento._ID, Contract.AgenteDescuento.COLUMN_CANAL, Contract.AgenteDescuento.COLUMN_LINEA,
                        Contract.AgenteDescuento.COLUMN_TOPE}
                , Contract.AgenteDescuento.COLUMN_CANAL + " = ? AND " + Contract.AgenteDescuento.COLUMN_LINEA + " = ? " , new String[] {canal + "", linea + ""});

        AgenteDescuento agenteDescuento = new AgenteDescuento();
        while(c.moveToNext()){
            agenteDescuento.setCanal(CursorUtils.getString(c, Contract.AgenteDescuento.COLUMN_CANAL));
            agenteDescuento.setLinea(CursorUtils.getString(c, Contract.AgenteDescuento.COLUMN_LINEA));
            agenteDescuento.setTope(CursorUtils.getDouble(c, Contract.AgenteDescuento.COLUMN_TOPE));
        }
        c.close();
        return agenteDescuento;
    }
}
