package rp3.berlin.models.pedido;

import android.database.Cursor;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import rp3.berlin.db.Contract;
import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;
import rp3.util.CursorUtils;

/**
 * Created by Gustavo Meregildo on 28/08/2017.
 */

public class PedidoTrazabilidad extends EntityBase<PedidoTrazabilidad> {

    private long id;
    private int _idPedido;
    private Date fecha;
    private String estado;


    @Override
    public long getID() {
        return id;
    }

    @Override
    public void setID(long id) {
        this.id = id;
    }

    @Override
    public boolean isAutoGeneratedId() {
        return true;
    }

    @Override
    public String getTableName() {
        return Contract.PedidoTrazabilidad.TABLE_NAME;
    }

    public int get_idPedido() {
        return _idPedido;
    }

    public void set_idPedido(int _idPedido) {
        this._idPedido = _idPedido;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Override
    public void setValues() {
        setValue(Contract.PedidoTrazabilidad.COLUMN_ID_PEDIDO, this._idPedido);
        setValue(Contract.PedidoTrazabilidad.COLUMN_FECHA, this.fecha);
        setValue(Contract.PedidoTrazabilidad.COLUMN_ESTADO, this.estado);
    }

    @Override
    public Object getValue(String key) {
        return null;
    }

    @Override
    public String getDescription() {
        return null;
    }
    public static List<PedidoTrazabilidad> getTrazabilidad(DataBase db, long idPedido) {
        Cursor c = db.query(Contract.PedidoTrazabilidad.TABLE_NAME, new String[] {Contract.PedidoTrazabilidad._ID, Contract.PedidoTrazabilidad.COLUMN_ID_PEDIDO,
                        Contract.PedidoTrazabilidad.COLUMN_FECHA, Contract.PedidoTrazabilidad.COLUMN_ESTADO}
                ,Contract.PedidoTrazabilidad.COLUMN_ID_PEDIDO + " = ? ", new String[]{idPedido + ""});

        List<PedidoTrazabilidad> list = new ArrayList<PedidoTrazabilidad>();
        while(c.moveToNext()){
            PedidoTrazabilidad detalle = new PedidoTrazabilidad();
            detalle.setID(CursorUtils.getInt(c, Contract.PedidoTrazabilidad._ID));
            detalle.set_idPedido(CursorUtils.getInt(c, Contract.PedidoTrazabilidad.COLUMN_ID_PEDIDO));
            detalle.setFecha(CursorUtils.getDate(c, Contract.PedidoTrazabilidad.COLUMN_FECHA));
            detalle.setEstado(CursorUtils.getString(c, Contract.PedidoTrazabilidad.COLUMN_ESTADO));
            list.add(detalle);
        }
        c.close();
        return list;
    }
}
