package rp3.berlin.models.pedido;

import rp3.data.entity.EntityBase;
import rp3.berlin.db.Contract;

/**
 * Created by magno_000 on 22/04/2016.
 */
public class TarjetaComision extends EntityBase<TarjetaComision> {

    private long id;
    private int idEmpresa;
    private int idMarcaTarjeta;
    private int idBanco;
    private int idTipoDiferido;

    @Override
    public long getID() {
        return id;
    }

    @Override
    public void setID(long id) {
        this.id = id;
    }

    @Override
    public boolean isAutoGeneratedId() {
        return true;
    }

    @Override
    public String getTableName() {
        return Contract.TarjetaComision.TABLE_NAME;
    }

    public int getIdBanco() {
        return idBanco;
    }

    public void setIdBanco(int idBanco) {
        this.idBanco = idBanco;
    }

    public int getIdTipoDiferido() {
        return idTipoDiferido;
    }

    public void setIdTipoDiferido(int idTipoDiferido) {
        this.idTipoDiferido = idTipoDiferido;
    }

    public int getIdEmpresa() {
        return idEmpresa;
    }

    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }

    public int getIdMarcaTarjeta() {
        return idMarcaTarjeta;
    }

    public void setIdMarcaTarjeta(int idMarcaTarjeta) {
        this.idMarcaTarjeta = idMarcaTarjeta;
    }

    @Override
    public void setValues() {
        setValue(Contract.TarjetaComision.COLUMN_ID_BANCO, this.idBanco);
        setValue(Contract.TarjetaComision.COLUMN_ID_TIPO_DIFERIDO, this.idTipoDiferido);
        setValue(Contract.TarjetaComision.COLUMN_ID_EMPRESA, this.idEmpresa);
        setValue(Contract.TarjetaComision.COLUMN_ID_MARCA_TARJETA, this.idMarcaTarjeta);
    }

    @Override
    public Object getValue(String key) {
        return idBanco;
    }

    @Override
    public String getDescription() {
        return null;
    }
}